qlik-oss/nebula.js

packages/serve/lib/engine.js
Docker compose fails when `ACCEPT_EULA=YES` is passed
=> fix: handle uppercase ACCEPT_EULA value

README.md, packages/serve/lib/engine.js, packages/serve/package.json
Starting `serve` should work on windows.
closes #44
=> fix: handle env variable on windows

packages/build/build.js, packages/build/package.json, yarn.lock
Attempt to use rollup-watch again since rebuilds are much faster compared to restarting the rollup builder.
This is more or less a revert of https://github.com/qlik-oss/nebula.js/commit/cc09554b62f322993b93fc2fae214f98ec49a291
At the time though we didn't use `rollup-plugin-node-resolve` with `customResolveOptions`, which caused issues during watch. Should hopefully work better from now on 🤞 .
=> chore(cli-build): use rollup watch for faster rebuilds

packages/nucleus/src/components/listbox/ListBoxPopover.jsx, packages/nucleus/src/components/selections/OneField.jsx, packages/nucleus/src/selections/app-selections.js
Fixes error being thrown because we're trying to change app selection state when an object is in modal state.
=> fix(nucleus): exit object modal state before modifying app state

packages/nucleus/src/index.js
Makes the nucleus API configurable to simplify reuse of same config for multiple apps:
The new `configured` method returns a new `nucleus` object that is preconfigured with the specified config.
**Before**:
```js
import nucleus from '@nebula.js/nucleus';
const n1 = nucleus(salesApp, {
theme: 'dark',
locale: {
language: 'en-US',
},
});
const n2 = nucleus(productsApp, {
theme: 'dark',
locale: {
language: 'en-US',
},
});
```
**After**:
```js
import nucleus from '@nebula.js/nucleus';
const darkEnglish = nucleus.configured({
theme: 'dark',
locale: {
language: 'en-US',
},
});
const n1 = darkEnglish(salesApp);
const n2 = darkEnglish(productsApp);
```
=> feat(nucleus): improve configurability

packages/serve/lib/webpack.serve.js
The `yarn start` included node_modules which yielded high cpu usage so let's ignore it.
=> build: ignore node_modules

apis/nucleus/src/sn/__tests__/type.spec.js, apis/nucleus/src/sn/type.js, apis/supernova/__tests__/unit/qae.spec.js, apis/supernova/package.json, apis/supernova/src/creator.js, apis/supernova/src/json-patch.js, apis/supernova/src/qae.js, commands/sense/src/supernova-wrapper.js, yarn.lock
This PR adds a simple API to observe when an object's properties are about to be changed and makes it possible to make additional changes:
```js
export default function supernova() {
return {
qae: {
properties: {
initial: { /* initial props */ },
onChange(properties) { // observe and make additional changes
if (properties.totalLabel) {
properties.qHyperCubeDef.qDimensions.forEach(dim => { dim.qTotalLabel = properties.totalLabel; });
}
},
},
data,
},
component: { }
};
}
```
=> feat: add property change observer

apis/nucleus/src/components/NebulaApp.jsx, apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxPopover.jsx, apis/nucleus/src/contexts/DirectionContext.js, apis/nucleus/src/index.js, commands/serve/web/components/App.jsx, commands/serve/web/contexts/DirectionContext.js
Add `direction` to api so we can handle it for example in the listbox popover
Notice that the tick is on the left side when using `rtl`
=> feat: add direction to api

apis/nucleus/src/object/get-object.js, apis/nucleus/src/object/observer.js, apis/nucleus/src/selections/app-selections.js, apis/nucleus/src/selections/object-selections.js, commands/create/templates/none/_package.json, commands/create/templates/none/test/integration/setup.int.js, commands/create/templates/picasso/barchart/test/integration/interaction.int.js, commands/create/templates/picasso/common/_package.json, commands/create/templates/picasso/common/test/integration/setup.int.js
Making selections in the app before the creation of the `current-selections` object is complete will cause that object to be aborted. This fixes that by waiting for the creation to be completed before making any selections.
Before:
After:
=> fix(nucleus): wait for curr selections

commands/serve/web/components/App.jsx, commands/serve/web/components/Cell.jsx, commands/serve/web/components/Chart.jsx, commands/serve/web/components/Collection.jsx, commands/serve/web/components/Stage.jsx
Rendering only one object has the limitation of only seeing a chart in its current temporary state and potentially missing out on a lot of different cases.
By rendering multiple objects of a certain type at the same time, it will hopefully make it easier to see how the charts behaves in various states:
=> feat(cli-serve): render existing objects

apis/supernova/__tests__/unit/creator.spec.js, apis/supernova/src/creator.js
When calling `onChange` function on `setProperties` or `applyPatches`, it's useful to have the model available (needed for expression modifiers).
This PR attaches the model to the `this` context of the `onChange` call.
=> feat(supernova): attach model when calling onChange

.circleci/config.yml
Saving the yarn cache on new branches/PR currently takes a little over 1min30sec. Ideally we would only want to save the cache on master but there doesn't seem to be an easy way without introducing multiple workflows with branch filters, so we'll try saving the cache without `{{ Branch }}` and see how that goes. This probably has the side-effect that changes to yarn.lock on PRs (like renovate) will override the cache on master :shrug:
=> ci: simplify cache hash

apis/nucleus/src/components/listbox/ListBox.jsx
For better UX let's skip `scrollToItem` when doing selections in the listbox
=> fix: skip scrollToItem in selections mode

commands/serve/web/components/App.jsx, commands/serve/web/components/AutoComponents.jsx, commands/serve/web/components/Properties.jsx, packages/ui/components/index.js, packages/ui/icons/index.js, packages/ui/theme/definitions/defaults.js
Generate a basic UI for object properties, it's fairly simple and limited at the moment, but it does make it easier to quickly modify property values.
relates to #34
=> feat(cli-serve): generate basic property panel

apis/nucleus/package.json, apis/nucleus/src/index.js
Polyfill async/await in nucleus to allow such syntax in supernovae
=> feat(nucleus): polyfill async await

commands/serve/lib/sn.js, commands/serve/package.json, yarn.lock
Preload `regenerator-runtime` to make sure it exists in serve environment before `snDefinition` is loaded
=> chore(cli-serve): preload regenerator-runtime

apis/nucleus/src/components/Cell.jsx, commands/serve/command.js, commands/serve/init-config.js, commands/serve/lib/serve.js, commands/serve/lib/webpack.serve.js, commands/serve/package.json, commands/serve/web/components/App.jsx, commands/serve/web/eRender.html, commands/serve/web/eRender.js, nebula.config.js, packages/ui/components/index.js, packages/ui/icons/index.js
Provide custom themes to the dev-server through a `nebula.config.js` file: 
```js
//nebula.config.js
module.exports = {
serve: {
themes: [ // provide custom themes to the dev-server
{
key: "pinkish",
theme: {
color: "deeppink",
type: "dark",
fontFamily: "Georgia"
}
}
]
}
};
```
The custom themes will then be available from a menu in the dev-server:
closes #142
=> feat(cli-serve): serve custom themes

commands/serve/lib/init-config.js, commands/serve/lib/webpack.serve.js, commands/serve/package.json
Enable static files to be served from '/assets' and makes it possible to e.g. serve local images.
=> feat(cli-serve): enable statically served files

apis/nucleus/src/components/selections/SelectedFields.jsx, apis/nucleus/src/components/selections/__tests__/selected-fields.spec.jsx
We should only keep modal state in app selections when a selected field is removed by deselecting last value.
=> fix: keep modal state

commands/build/command.js, commands/build/lib/build.js, commands/build/lib/init-config.js, commands/build/package.json, commands/serve/lib/serve.js, test/integration/setup.int.js, yarn.lock
- Inject default options for build config
- Remove `resolveOptions` from rollup-plugin-node-resolve to allow the default node-resolve algorithm to do its magic
- Add rollup-plugin-commonjs to enable resolution of cjs modules
=> feat(cli-build): support config

commands/serve/lib/head-injector.js, commands/serve/lib/init-config.js, commands/serve/lib/webpack.build.js, commands/serve/lib/webpack.prod.js, commands/serve/lib/webpack.serve.js
Makes it possible to inject scripts and stylesheets into the head of cli-serve. Useful in case there are external css dependencies like fonts that need to be loaded, or if some script needs to run before the rest of the page.
```sh
nebula serve --assets static --stylesheets /assets/fonts.css --scripts /assets/foo.js
```
=> feat(cli-serve): add option to inject script and stylesheet

apis/nucleus/src/components/listbox/ListBoxPopover.jsx, apis/nucleus/src/components/listbox/ListBoxSearch.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-search.spec.jsx, apis/nucleus/src/selections/object-selections.js
- switch lock icon to show current state
- disable other actions when locked
- add padding to actions
- update search input styling
- update more dropdown shadow
_|Before|After
---|---|---
Search|![search-before](https://user-images.githubusercontent.com/16324367/69815115-eda69b00-11f5-11ea-9fb8-89e9a482a1d2.png)|![search-after](https://user-images.githubusercontent.com/16324367/69815114-eda69b00-11f5-11ea-9453-ca127c6ce0ab.png)
Dropdown|![more-before](https://user-images.githubusercontent.com/16324367/69815129-f5663f80-11f5-11ea-92ab-68c3a25c3078.png)|![more-after](https://user-images.githubusercontent.com/16324367/69815127-f5663f80-11f5-11ea-8570-3561502b8c60.png)
=> fix: update styling for listbox popover

packages/ui/theme/create.js, packages/ui/theme/definitions/defaults.js
mui uses touchripple to highlight when a component receives focus, since we disable the ripple in this project we need to add custom styling when elements are focused.
Some components can be styled using `$focusVisible` which [should be used when possible](https://github.com/WICG/focus-visible/blob/master/explainer.md), otherwise `:focused` can be used.
=> fix: add focus style on icon buttons

apis/nucleus/src/__tests__/app-theme.spec.js, apis/nucleus/src/__tests__/nucleus.spec.js, apis/nucleus/src/object/__tests__/create-object.spec.js, apis/nucleus/src/object/__tests__/hc-handler.spec.js, apis/nucleus/src/object/__tests__/populator.spec.js, apis/nucleus/src/sn/__tests__/type.spec.js, apis/nucleus/src/sn/__tests__/types.spec.js, apis/supernova/__tests__/unit/creator.spec.js, apis/supernova/__tests__/unit/generator.spec.js
Multiple mocks in the same file messes up coverage stats, only one mock should be used.
=> test: remove multiple mock

apis/nucleus/src/__tests__/viz.spec.js, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/__tests__/cell.spec.jsx, apis/nucleus/src/viz.js, commands/serve/web/components/Cell.jsx, commands/serve/web/eRender.js
- fixes snapshot rendering in cli-serve /render
- remove attaching `snapshotData` by default - nebula has no use for this, charts should attach this property if they're using it.
=> fix(cli-serve): export image

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxPopover.jsx, apis/nucleus/src/selections/__tests__/object-selections.spec.js, apis/nucleus/src/selections/object-selections.js
- fix 'more selection menu' being invertly disabled
- do not send traffic to select when field is locked
- do clearSelections instead of resetMadeSelections for listbox
- disable lock icon when no selections made
- add unit tests for object-selections
=> fix: listbox selection actions

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/__tests__/cell.spec.jsx
Use first targets property path instead of hard coded `qHyperCubeDef` when going into modal mode.
=> feat: use first target property path

apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/hooks.js, apis/supernova/src/index.js, test/component/hooks/sn.comp.js
=> feat: add lazy layout hook

apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/creator.js, apis/supernova/src/hooks.js, apis/supernova/src/index.js, test/component/hooks/hooked.fix.js, test/component/hooks/sn.comp.js
useAction that enables adding custom actions into an object's selection toolbar or a future more generic object toolbar.
```js
const [count, setCount] = useState(0);
const [act] = useAction(() => ({
action() {
setCount(c => c + 1)
},
enabled: true
}));
```
=> feat: useAction hook

commands/serve/lib/webpack.build.js, commands/serve/web/components/App.jsx
This adds alias for production and MONO so we end up using same file scope
which is key for our `stores` used by for example `useRpc`
=> fix(cli-serve): ensure using same file scope

apis/test-utils/index.js, apis/test-utils/package.json, apis/test-utils/src/index.js, rollup.config.js
With hooks and the functional approach it is a bit trickier to test a component since there is no instance to verify properties on, adding test-utils makes it possible to unit test a functional component:
```js
import { useElement, useState } from '@nebula.js/supernova';
function component() {
const element = useElement();
element.innerHTML = 'foo';
}
```
```js
import { create } from '@nebula.js/test-utils';
import component from './component';
describe(() => {
it('should add foo',  async () => {
const mockedThings = {
layout: 'meh',
element: {},
};
const c = create(component, mockedThings);
await c.update();
expect(mockedThings.element.innerHTML).to.equal('foo');
});
});
```
=> feat: add test-utils package

apis/nucleus/package.json, apis/nucleus/src/index.js, apis/supernova/package.json, apis/supernova/src/index.js
Since supernova now is a peer dependency to nucleus it will be the first module imported - polyfills should therefore be registered by supernova instead of nucleus.
=> fix(cli-serve): add regenerator-runtime polyfill

apis/nucleus/package.json, apis/nucleus/src/sn/__tests__/type.spec.js, apis/nucleus/src/sn/type.js, yarn.lock
Rollback `semver` to `6.x.0` to avoid circular dependencies, which cisandbox doesn't seem to be able to handle
=> chore(deps): rollback semver major version

apis/nucleus/src/components/Cell.jsx, apis/snapshooter/lib/snapshooter.js, commands/serve/lib/snapshot-router.js, commands/serve/lib/webpack.serve.js
read and serve custom snapshots from `nebula.config.js` to allow simple testing without backend:
```js
// nebula.config.js
module.exports = {
serve: {
snapshots: [{
key: 'basic',
meta: {
size: { width: 600, height: 600 },
language: 'sv-SE',
theme: 'dark',
appLayout: { qLocaleInfo: {} },
},
layout: {
showTitles: false,
qHyperCube: {}
}
}]
}
}
```
A given snapshot can be provided as a query parameter under the /render route in order to render the supernova without a data backend, e.g. `http://localhost:8000/render/?snapshot=basic`
=> feat(cli-serve): serve custom snapshots

commands/serve/web/eHub.html
When a lot of apps appeared in the hub, the bottom ones could become unaccessible.
=> fix(cli-serve): show scrollbar in hub

apis/nucleus/package.json, apis/test-utils/package.json, examples/sn-hello-react/package.json, packages/ui/package.json
Very little use in having locked version of peer dependencies, should simply specify the range that is required
=> chore(deps): avoid lock on peer dependencies

apis/nucleus/__tests__/unit/selectiontoolbar.spec.jsx, apis/nucleus/src/components/Header.jsx, apis/nucleus/src/components/SelectionToolbar.jsx, apis/nucleus/src/components/SelectionToolbarItem.jsx, apis/nucleus/src/components/__tests__/selectiontoolbaritem.spec.jsx, apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/hooks.js
Show custom actions in Object selection toolbar:
=> feat(nucleus): show action in selection toolbar

commands/serve/lib/serve.js
Simplify the code by using the path.basename function
=> refactor(cli-serve): use path.basename

apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/hooks.js
Fixes incorrect check for multiple `useImperativeHandle`.
=> fix(supernova): fix incorrectly thrown error

apis/nucleus/src/object/__tests__/hc-handler.spec.js, apis/nucleus/src/object/hc-handler.js, commands/serve/web/components/property-panel/HyperCube.jsx
The hypercube/measure/dimension definition should have the default object/array properties injected to make it easier to modify those properties at deeper levels.
=> fix(supernova): inject default property values

commands/build/lib/build.js, commands/serve/lib/webpack.serve.js
- log status when using watch with `build`
- reset error overlay when build is successful again
fixes #36
=> feat(cli-serve): log build result on watch

commands/build/lib/build.js
Ensures that any logged warnings of a build are not cleared from screen when the build is successful
=> fix(cli-build): log warnings

apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/hooks.js, test/component/hooks/hooked.fix.js
BREAKING CHANGE: returned value from useAction and useRect now return a single value instead of an array
=> refactor(supernova): change return value for useAction and useRect

apis/supernova/__tests__/unit/creator.spec.js, apis/supernova/src/creator.js
Since `options` is an object that could contain anything including classes, methods and cyclical references, we can't really use JSON parse to do a deep check of it.
So do a shallow reference check on the properties inside it instead that should be sufficient
=> fix(supernova): avoid deep check on options

aw.config.js
This excludes root files which only requires different bundles depending on productions vs development
=> test: exclude files

apis/supernova/__tests__/unit/creator.spec.js, apis/supernova/src/creator.js
Fix issue where a call to `render` that takes time could be circumvented by calling another `render` with the same parameters. Since the second call does not contain any changes, we would return an already resolved promise even if the previous call was still unresolved.
Fix it by storing the return value from the last changed call and return that when `render` is called without changes.
=> fix(supernova): return value from last run

apis/nucleus/src/hooks/__tests__/use-app-selections.spec.jsx, apis/nucleus/src/hooks/useAppSelections.js, apis/nucleus/src/hooks/useObjectSelections.js, apis/nucleus/src/stores/selectionsStore.js
This ensures handling fast selections and fast confirm by separating `switchModal` into `begin` `end` and only use what is needed in the different scenarios
BREAKING CHANGE: Also removed the `switchModal` e.g app modal state handling from app selections API
=> fix: race condition in selections confirm

apis/nucleus/src/hooks/useAppSelections.js
Set current modal only after successful `beginSelections`
=> fix(use-app-selections): set modal on successful `beginSelections` only

apis/supernova/__tests__/unit/creator.spec.js, apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/creator.js, apis/supernova/src/hooks.js
Since ResizeObserver isn't available in IE11 and Edge we need a way to explicitly trigger a resize of a component.
=> fix(supernova): enable exlicit resize

apis/nucleus/src/index.js
BREAKING CHANGE: Only support `mount` / `unmount`
=> chore: remove `appSelections`

commands/serve/docker-compose.yml, commands/serve/lib/serve.js, commands/serve/web/hot.js
Fix loading remote supernovae e.g
`--entry https://unpkg.com/@nebula.js/sn-mekko-chart`
and bump engine docker version
=> fix: load remote supernova

apis/nucleus/src/__tests__/app-theme.spec.js, apis/nucleus/src/app-theme.js, apis/nucleus/src/index.js, commands/serve/lib/webpack.serve.js
Use `id` instead of `key` when working with themes.
BREAKING CHANGE: use id instead of key
=> refactor: change `theme.key` to `theme.id`

apis/supernova/__tests__/unit/qae.spec.js, apis/supernova/src/qae.js
Building a chart that doesn't use either dimensions or measures will still get these injected into the qae definition. For example it defaults to allowing any number of dimensions.
Discussion: Should we instead check for "max: 0" and exclude them then?
=> feat: make dims and measures optional in qae

apis/nucleus/spec/spec.json, apis/nucleus/src/__tests__/nucleus.spec.js, apis/nucleus/src/index.js, apis/supernova/spec/spec.json, commands/serve/web/eRender.js, test/mashup/snaps/configured.js
API polishing 💅 
BREAKING CHANGE: Use `nucleus.createConfiguration` instead of `nucleus.configured`
=> refactor(nucleus): rename `configured` to `createConfiguration`

commands/serve/lib/init-config.js, commands/serve/lib/serve.js, commands/serve/lib/webpack.serve.js
To be able to use the browserless docker (on mac, win) run:
nebula serve --host "0.0.0.0" --disable-host-check --enigma.host "host.docker.internal"
Run browserless:
```sh
docker run -d -p 3000:3000 --rm --name chrome browserless/chrome:1.28.0-puppeteer-1.20.0
```
Running integration tests with:
APP_ID="the-app-id" BASE_URL="http://host.docker.internal:8000" yarn test:integration --chrome.browserWSEndpoint "ws://localhost:3000" --no-launch
=> chore: support running browserless locally

apis/nucleus/src/components/Supernova.jsx
Ensure having a container rect before rendering else we can get an initial render and then directly another one when the container rect changes.
=> fix: wait for container rect

commands/build/README.md, commands/build/lib/build.js, commands/build/lib/init-config.js
For integrated uses of the built packages we sometimes need to disable sourcemaps, this adds an option to do that via the build command.
=> feat(cli-build): add sourcemaps option to build

aw.config.js
Exclude the `locale` and `theme` package entry point since it only required the production or dev entry point.
=> test: exclude locale and theme entry point

apis/nucleus/src/components/selections/More.jsx
Ensure color `inherit` on the `More` item
=> fix: use color `inherit`

apis/nucleus/src/__tests__/nucleus.spec.js, apis/nucleus/src/flags/flags.js, apis/nucleus/src/index.js, apis/nucleus/src/sn/__tests__/load.spec.js, apis/nucleus/src/sn/load.js, apis/nucleus/src/sn/type.js, apis/supernova/__tests__/unit/creator.spec.js, apis/supernova/src/creator.js, apis/supernova/src/generator.js, apis/supernova/src/hooks.js, test/component/hooks/hooked.fix.js, test/component/hooks/sn.comp.js
Add possibility for feature toggling:
```js
// in nucleus config
nucleus(app, {
flags: {
MONKEY_DANCE: true
}
});
```
```js
// consume in supernova
export function function s({ flags }) {
if (flags.isEnabled('MONKEY_DANCE')) {
return dancingMonkey();
}
return boringMonkey();
}
```
resolves #380
=> feat(nucleus): add flags api

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/__tests__/cell.spec.jsx
This ensures show the loaders exclusively.
Also add test for `exportImage`
=> fix: only show `<Loading />` or `<LongRunningQuery />`

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/hooks/__tests__/use-rect.spec.jsx, apis/nucleus/src/hooks/useRect.js
Revert `useRect` for now since it was prematurely changed.
=> fix: revert `useRect`

apis/nucleus/src/components/Cell.jsx
This ensures having `cellRect` before exposing `takeSnapshot`
=> fix: add `cellRect` to dependencies

.circleci/config.yml, apis/nucleus/src/hooks/__tests__/use-app-selections.spec.jsx, apis/nucleus/src/hooks/__tests__/use-object-selections.spec.jsx, apis/nucleus/src/hooks/useAppSelections.js, apis/nucleus/src/hooks/useObjectSelections.js
Remove superfluous `abortModal` from `appSelections` and `objectSelections`.
BREAKING CHANGE: `appSelections.abortModal` and `objectSelections.abortModal` removed.
=> refactor: remove `abortModal`

commands/serve/lib/webpack.serve.js, commands/serve/web/eRender.js
This enables to pass render configs via `nebula.config.js`
```
serve: {
renderConfigs: [{
id: "test123",
render: {
fields: ["Month", "=sum(Sales)"],
}
}],
}
```
In your integration test you can then use
```
await page.goto(`${process.env.BASE_URL}/render/?app=${app}&render-config=test123`);
```
=> test: support render configs

.codesandbox/mekko/src/init.js, apis/nucleus/src/__tests__/viz.spec.js, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/__tests__/cell.spec.jsx, apis/nucleus/src/index.js, apis/nucleus/src/object/__tests__/create-session-object.spec.js, apis/nucleus/src/object/__tests__/initiate.spec.js, apis/nucleus/src/object/create-session-object.js, apis/nucleus/src/object/initiate.js, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, commands/serve/web/components/App.jsx, commands/serve/web/components/Cell.jsx, commands/serve/web/eRender.js, test/mashup/snaps/snapper.js
Move internal APIs into a `__DO_NOT_USE__` variable to make it clear it's internal and should not be used.
=> refactor: move internal APIs into a __DO_NOT_USE__ variable

.circleci/config.yml, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/Supernova.jsx, apis/nucleus/src/object/get-object.js, apis/snapshooter/server.js, apis/stardust/api-spec/spec.conf.js, apis/stardust/api-spec/spec.json, commands/create/templates/sn/none/test/integration/hello.int.js, commands/create/templates/sn/picasso/barchart/test/integration/interaction.int.js, test/component/hooks/sn.comp.js, test/component/object/sn.comp.js, test/integration/sn.int.js, test/mashup/snaps/snapper.int.js
Shorten class names.
BREAKING CHANGE: rename nebulajs-cell to njs-cell and nebulajs-sn to njs-viz
=> refactor: rename public classnames

commands/sense/lib/build-legacy.js
Avoid removing the target directory when building a Sense extension since this could easily cause unwanted removal of directories if the wrong output path is provided.
=> fix(cli-sense): do not remove target dir

apis/nucleus/src/hooks/__tests__/use-rpc.spec.jsx, apis/nucleus/src/hooks/useRpc.js
Add existing result on `cancel` to ensure we keep existing `layout`'
=> fix: add existing result on `cancel`

apis/nucleus/src/components/Error.jsx
Remove the spacing attribute on the Grid in `Error.jsx` which caused misalignment.
=> fix: remove spacing in `Error.jsx`

commands/serve/web/connect.js
fix `.getConfiguration is not a function` error when a SaaS endpoint is being used.
=> fix(cli-serve): mock getConfiguration

apis/nucleus/src/components/listbox/ListBox.jsx
`qOneAndOnlyOne` should work when selecting values in a listbox.
=> fix: handle qOneAndOnlyOne for listbox selections

apis/theme/src/__tests__/set-theme.spec.js, apis/theme/src/set-theme.js
When a sense theme incorrectly includes empty arrays for palettes they end up as empty in the finished theme, even with inheritance enabled.
=> fix(theme): add additional palette fallback

apis/nucleus/src/components/__tests__/glue.spec.jsx, apis/nucleus/src/components/glue.jsx
previous it was only removed if the unmount was caused by a closed model
=> fix: remove listener on unmount

apis/nucleus/src/hooks/__tests__/use-object-selections.spec.jsx, apis/nucleus/src/hooks/useObjectSelections.js
don't clear an empty range select
disable clear and confirm button when the selection is cleared
improved selections experience and match how it works inside qlik-sense
=> fix: object-selections

.circleci/config.yml
Disable API-gov check for forked PRs
=> chore: skip api-gov job on forks

apis/nucleus/src/components/ActionsToolbar.jsx
As it is not a menu that you open use and close but it open a longer time it should not block focus.
A specific problem it that without this fix it prevent editing values in range select bubbles
=> fix(nucleus): disable enforce focus on actions toolbar

.circleci/config.yml, apis/conversion/src/export-format.js, apis/conversion/src/hypercube/index.js, apis/conversion/src/index.js, apis/nucleus/src/__tests__/viz.spec.js, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-column.spec.jsx, apis/nucleus/src/index.js, apis/nucleus/src/object/create-session-object.js, apis/nucleus/src/object/populator.js, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/supernova/src/qae.js
Continueation of #548 
- Adds support for master dimensions
- Adds test case for inline listbox
=> fix: support master dims

commands/serve/web/connect.js
The dev environment is not working which can create some frustration since the solution is not obvious. The issue comes from having spaces in the `engineUrl`. Therefore, we need to trim the URL before using it.
=> fix: trim whitespace before using url -

apis/test-utils/src/index.js
I don't know if this is the right way to expose this.
alternative could be to
* use a different name for updateRectOnNextUpdate
* always call hooked.updateRectOnNextRun(component); in update
* call hooked.updateRectOnNextRun(component); in update if specified in an argument
* a resize method that calls hooked.updateRectOnNextRun(component); and update
=> feat(test-utils): support testing components using useRect

.circleci/config.yml, apis/nucleus/src/components/ActionsToolbar.jsx, commands/serve/docker-compose.yml, test/fixtures/docker/docker-compose.yml
When starting selections and the ActionsToolbar shows up, it steals focus. It also set focus to where it was before opening when it closes. This is disruptive for the sn-table since you want to stay inside the table, then potentially tab to the toolbar when you want to confirm/cancel selections.
=> fix: make sure ActionsTooblar doesn't steal focus

commands/build/README.md, commands/build/lib/build.js, commands/build/lib/init-config.js
Possibility to explicitly override `mode` option (`development` or `production`) used for the rollup config. This allows user to get everything minified (even the core package).
=> feat(cli-build): add mode option to build

.circleci/config.yml
Temporarily disable api governance until we can get the spec validation up to date.
=> chore: temp disable api gov

commands/build/lib/init-config.js
Solves an issue causing a crash with the message _"Invalid JSON config file: nebula.config.js"_ when running `nebula serve` with a `nebula.config.js` file without a `build` section.
The issue was introduced with #625 and the lines:
```
const yargsArgs = argv.config ? ['--config', argv.config] : [];
defaultBuildConfig = initConfig(yargs(yargsArgs)).argv;
```
(The problem could probably occur in other scenarios as well, but this fix should take care of the problem)
=> fix: do not return undefined build config

commands/sense/src/legacy/__tests__/selections.spec.js, commands/sense/src/legacy/selections.js
support selections.begin(paths) when wrapped in an sense extension
(it is already supported when used in nebula.js outside sense. [link](https://github.com/qlik-oss/nebula.js/blob/bd39cb4b4d66ac5153083046f0a511263a7095ba/apis/nucleus/src/hooks/useObjectSelections.js#L37))
=> fix(extension-wrapper): support paths argument in begin

commands/sense/lib/build.js, commands/sense/src/ext.js
The "--partial" build didn't handle the "--ext" command correctly as the resulting package couldn't find the ext file. I corrected the path and added a check for an edge case where the ext file is an es module but contains multiple exports (sn-table has this for example to do unit tests)
=> chore: handle --ext edge case

apis/nucleus/src/__tests__/nucleus.spec.js, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/Error.jsx, apis/nucleus/src/components/Loading.jsx, apis/nucleus/src/components/LongRunningQuery.jsx, apis/nucleus/src/components/Supernova.jsx, apis/nucleus/src/components/__tests__/supernova.spec.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/index.js, apis/nucleus/src/sn/__tests__/types.spec.js, apis/nucleus/src/sn/types.js, apis/stardust/api-spec/spec.json, apis/stardust/src/index.js, apis/supernova/__tests__/unit/creator.spec.js, apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/creator.js, apis/supernova/src/hooks.js, apis/supernova/src/index.js, commands/serve/web/components/App.jsx, commands/serve/web/components/Collection.jsx, commands/serve/web/components/Stage.jsx, packages/ui/theme/create.js, test/component/hooks/hooked.fix.js, test/component/hooks/sn.comp.js
Adds a useEmbed hook allowing charts to embed other charts.
- useEmbed
- expose embed for non hooked charts
- expose getRegisteredTypes
- adds fallback for missing chart versions
- remove auto modal for inline listbox (not relevant to the rest, just a fix)
Todo
=> feat: give charts access to the nebula instance

commands/serve/README.md, commands/serve/lib/webpack.serve.js, commands/serve/web/components/App.jsx, commands/serve/web/hot.js
Allows for the serve configuration to register extra types to the embed instance:
```
module.exports = {
serve: {
types: [{ name: 'barchart', url: "https://unpkg.com/@nebula.js/sn-bar-chart"}],
},
};
```
This allows an chart to render the extra types using `useEmbed`.
Todo:
=> feat: add types to nebula serve

apis/nucleus/src/components/Supernova.jsx, apis/nucleus/src/utils/__tests__/render-debouncer.spec.js, apis/nucleus/src/utils/render-debouncer.js
If the rendering of an object took long time it was possible to skip updates and end up with a last render call that was not up to date with the latest layout.
Only seen in objects that modify its on properties on render
Simple example supernova with this problem:
```
function randomValue() {
return Math.floor(Math.random() * 100);
}
export default function supernova() {
return {
component() {
const layout = useStaleLayout();
const element = useElement();
const model = useModel();
const [value] = useState(() => randomValue());
const str = `The value is: ${value}`;
const text = layout.text || 'Hello!';
usePromise(async () => {
if (str === text) {
return;
}
const props = await model.getProperties();
props.text = str;
await model.setProperties(props);
await model.getLayout();
}, [layout]); …
```
=> fix: do not skip all updates if the rendering take long time

apis/nucleus/src/components/Supernova.jsx, apis/stardust/src/index.js, apis/supernova/src/hooks.js, apis/supernova/src/index.js
Add useRenderState hook
Used to update properties and get a new layout without triggering onInitialRender.
=> feat: useRenderState hook

commands/serve/web/connect.js
Currently we fetch not only apps when running `nebula serve`, which means you also get datasets. Chaning this to filter on resourceType=app
=> fix: only fetch apps from qlikcloud

commands/serve/web/components/App.jsx
Noticed that the types weren't actually registered correctlöy, it just happend to work anyway as the load function was seperated out. If you added more that one extra type it broke. This fixes that.
=> fix: bug in serve types

.circleci/config.yml
should we remove the ignore in renovate.json?
=> chore: bump node version used in cicleci

commands/build/lib/build.js
This addresses an issue that was seen after updating `@rollup/plugin-commonjs` from 20.0.0 -> 21.0.1.
See https://github.com/rollup/plugins/issues/1004 for more info around it.
=> fix(cli-build): mitigate problem with require inside try catch blocks

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxColumn.jsx, apis/nucleus/src/components/listbox/ListBoxRow.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-column.spec.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-row.spec.jsx, apis/nucleus/src/components/listbox/__tests__/list-box.spec.jsx, apis/nucleus/src/components/listbox/__tests__/listbox-selections.spec.js, apis/nucleus/src/components/listbox/__tests__/use-selections-interactions.spec.jsx, apis/nucleus/src/components/listbox/listbox-selections.js, apis/nucleus/src/components/listbox/use-selections-interactions.js, apis/nucleus/src/components/listbox/useSelectionsInteractions.js
- Get instant selection feedback on click (replaced by `onMouseDown`) by modifying the pages directly for better user experience
- This is also needed for range selections (next PR)
=> refactor(listbox): instant selection feedback on click

.prettierignore, apis/stardust/README.md, apis/stardust/api-spec/spec.conf.js, apis/stardust/api-spec/spec.json, apis/stardust/package.json, apis/stardust/types/index.d.ts, apis/supernova/src/qae.js, rollup.config.js, yarn.lock
Generate typescript definitions from the API specification using `@scriptappy/to-dts`.
In a number of information related to Qlik Engine is used. The typescript definitions published at [@types/qlik-engineapi](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/qlik-engineapi) is used to these cases. The type script definitions includes a [reference](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) to the Engine API:
```ts
/// <reference types="qlik-engineapi" />
```
In order for the typescript definition to be valid the package `@types/qlik-engineapi` needs to be installed. The package is added as a dependency to stardust in order to get it installed automatically.
https://user-images.githubusercontent.com/7684435/152536769-5a836a2b-cfea-434e-bf4 …
=> feat(stardust): generate typescript definitions

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxCheckbox.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/ListBoxRowColumn.jsx, apis/nucleus/src/components/listbox/ListBoxSearch.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-row-column.spec.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-search.spec.jsx, apis/nucleus/src/index.js
Add `dense` option for listbox component. When running in dense mode the padding and text size is reduced.
Add static class names to the search input and for each value. The class names are `search` and `value`. This enables possibility to override styling.
*Normal mode (as-is today)*
*Dense mode*
*With custom styling*
=> feat(listbox): dense mode with reduced padding and text size

apis/nucleus/src/index.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/supernova/src/hooks.js, docs/api-reference.md
```
embed(app, {
constraints: {
active: true, // do not allow interactions
}
})
```
should be
```
embed(app, {
context: {
constraints: {
active: true, // do not allow interactions
}
}
})
```
```
const d = m.createConfiguration({
theme: 'dark'
});
```
should also be
```
const d = m.createConfiguration({
context: {
theme: 'dark'
}
});
```
=> docs: add missing context in createconfiguration

apis/nucleus/src/components/listbox/listbox-highlight.js, apis/nucleus/src/components/listbox/listbox-selections.js, apis/nucleus/src/index.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
Update JSDoc to improve API specification and typescript definitions. Changes:
* Add types for ListBox options containing fixed set of valid configs. For example, `FrequencyMode` and `Direction`.
* Use `@interface` to describe objects with a number of properties (instead of `@typedef`)
=> fix: update jsdocs for listbox

.codesandbox/mekko/package.json, commands/create/templates/mashup/_package.json, examples/chart-conversion/package.json, examples/dev-mashup/package.json
Updates Parcel from the RC to 2.3.2 for all packages. Also adds the `--no-hmr` option which resolves issues with `yarn link`-ing local stardust versions
=> chore: update parcel and bypass hmr bug

.circleci/config.yml
The `machine:true` setting in cirlce is getting deprecated, so replacing it.
=> chore: replace deprecated build image

apis/supernova/src/hooks.js, apis/theme/src/__tests__/style-resolver.spec.js, apis/theme/src/index.js, apis/theme/src/style-resolver.js
…
Like in https://github.com/qlik-oss/sn-table/pull/453, sometimes we want to get a style value by exact search without a fallback.
When attributes separated by dots is provided, such as 'hover.color', they are required in the theme JSON file
Ex.
`const hoverFontColorFromTheme = theme.getStyle('object', 'straightTable.content', 'hover.color');`
that would require a hover: { color: ... } } in the theme but still fallback to look for that on multiple levels, supporting a theme with a global hover.color fallback.
and if you want more exact you can just call
`const hoverFontColorFromTheme = theme.getStyle('object', '', 'straightTable.content.hover.color');`
=> feat: get the value of style with the exact given attributes seprated by dots 

apis/enigma-mocker/src/__tests__/prop.spec.js, apis/enigma-mocker/src/from-generic-objects.js, apis/enigma-mocker/src/mocks/get-object-mock.js, apis/enigma-mocker/src/prop.js, apis/nucleus/src/components/LongRunningQuery.jsx, test/mashup/visualize/life.int.js, test/mashup/visualize/scenarios.js
Adds a test for long runnning queries by adding a delay to the mocked engine calls. It currently doesn't properly cancel the call when you press cancel (or the test presses cancel), but it covers the functionality.
@streamside Feel free to clean up this code if you like, had to do some light hacking to get the delay to work without slowing everything down too much.
=> chore: add long running test

commands/build/lib/build.js, commands/build/package.json, commands/cli/lib/index.js
cli-build would throw errors if certain typescript libraries wasn't present in the current node_modules scope, this attempts to remedy that and throw better errors.
=> chore: make typescript optional in build

apis/nucleus/src/components/Cell.jsx
Fix [an issue in the mashup development using sn-table 
](https://github.com/qlik-oss/sn-table/issues/570) 
- missing the selections in dependency arrays causes the value of `selections` in 
```
loadType({
dispatch,
types,
visualization,
version,
model,
app,
selections,
nebbie,
focusHandler: focusHandler.current,
}); 
```
is undefined
- then `params.selections` is undefined
```
create(params) {
const ss = create(generator, params, galaxy);
return ss;
},
``` 
in generator.js
- then `opts.selections` is undefined
```
function createWithHooks(generator, opts, galaxy) {
const c = {
context: {
selections: opts.selections,
}
}
}
``` 
in creator.js
- then `useSelections() `is undefined
```
export function useSelections() {
return useInternalContext('selections');
}
```
in hooks.js
***OR***
When …
=> fix: the selections is missing in dependency arrays

apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/useConfirmUnfocus.jsx, apis/nucleus/src/index.js
Temporary fix to disable confirming selections on blur events. This should eventually be refactored, see issue #863
***OR***
=> fix(listbox): prop to disable confirming selections on blur events

apis/nucleus/src/components/listbox/ListBoxSearch.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-search.spec.jsx
"Fix" for https://jira.qlikdev.com/browse/QB-10955 to disable select on enter keystroke
***OR***
=> fix: disabling on enter select on listbox searches

apis/nucleus/src/components/listbox/ListBox.jsx
Listbox fetch It’s only listening to changes on layout.. but since layout.qListObject.qSize.qcy is deep inside the object structure it’s not reacting on qSize.qcy changing when searching
***OR***
=> fix: filterBox react on qsize.qcy change when searching

apis/nucleus/src/components/listbox/ListBoxSearch.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-search.spec.jsx
Should not call Abort if we aren't actively searching
***OR***
=> fix: listbox abort search only if is searching

apis/nucleus/src/components/listbox/ListBox.jsx
- fixed height calculation issue while scrolling for listbox by modifying the payload of call from engine.
- synced `itemsCount` for `<StyledInfiniteLoader />`  with `<FixedSizeList />`
***OR***
=> fix: correct height calculation of listbox

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/__tests__/list-box.spec.jsx
When `<InfiniteLoader />` gets `0` items, it will never fetch data again (it will not call `loadMoreItems`). Therefore, this value should always be `> 0`. This solves both the previously solved search issue (no hits) and the issue where zero items blocks new requests.
***OR***
=> fix(ListBox): Prevent empty list because of 0 items

commands/serve/lib/init-config.js, commands/serve/lib/webpack.build.js, commands/serve/package.json, commands/serve/web/components/App.jsx, commands/serve/web/components/AutoComponents.jsx, commands/serve/web/components/FieldsPopover.jsx, commands/serve/web/components/Properties.jsx, commands/serve/web/components/property-panel/Variable.jsx
Currently the cli-serve dev environment doesn't show property panel controls for all properties. For example all q-Props are skipped. This PR adds 
- exception for qStringExpressions: these will show up as a text field with a '=' appended
- support for variables of specific property structure:
```
variable: { name: '', value: '' }
```
Where value will be a qStringExpression trying to evaluate the variable.
***OR***
=> feat: add variable and expression support to serve props

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxRowColumn.jsx, examples/dev-mashup/package.json
Minor fixes for the Listbox:
- Add back the styled scrollbar to get a cross-browser fixed width (stopped working after the mui5 update)
- Remove the `main` property in package.json to prevent parcel build error
***OR***
=> fix: get back the styled scrollbar

apis/nucleus/src/components/listbox/ListBox.jsx
The direction prop for listbox is quite confusing if you don't read the API, as when passed as "horizontal" into the FixedList it will display as horizontal. It should actually only take the form of rtl/ltr, so now we'll explicitly check that.
=> fix: add check for rtl-ltr for direction prop

docs/installation.md
Prevent a common mistake when linking repos using `nebula serve` by documenting it here: https://github.com/qlik-oss/nebula.js/blob/master/docs/installation.md 
***OR***
=> docs: linking nebula docs

commands/build/lib/build.js
Add build using systemjs format which for example can be used in MFE context.
Changes:
* Add systemjs build which is performed when the property `systemjs` in `package.json` specifies where to output the bundle. No build performed in case no filename is present.
* Configure external dependencies. Specify an array at path `systemjs.external` in `nebula.config`.
* Refactor: Inject variations in behaviour per build format to `config()` in order to prevent if/elseif/else for each format. Each format specifies, for example, what the output file name should be.
* Refactor: Rename UMD build to `umd` (was `minified` which made more sense when there was only one format to build) 
***OR***
=> feat(build): add system js build

commands/build/README.md, commands/build/lib/build.js, commands/build/lib/init-config.js
Add support to output build on SystemJS format when watching.
Examples how to use it:
```sh
// Output build on UMD format (as-is today)
nebula build --watch
// Specify UMD format explicitly
nebula build --watch umd
// Specify SystemJS format
nebula build --watch systemjs
```
In case no `systemjs` bundle is specified in package.json the command fails gracefully informing the user about the problem.
***OR***
=> feat(build): watch systemjs build

apis/enigma-mocker/src/from-generic-objects.js, apis/enigma-mocker/src/index.js, apis/enigma-mocker/src/mocks/get-object-mock.js, apis/enigma-mocker/src/prop.js, apis/nucleus/src/components/listbox/useConfirmUnfocus.jsx, apis/stardust/api-spec/spec.conf.js, apis/stardust/api-spec/spec.json, apis/stardust/src/index.js, apis/stardust/types/index.d.ts
To allow us to start using the enigma mocker in examples I've moved it to the public API as experimental.
***OR***
=> feat!: move enigma mocker to public api

commands/create/templates/mashup/_package.json, commands/create/templates/mashup/src/connect.js
integrating the nebula mashup template to use `@qlik/sdk` pkg instead of old solution(`csrf-token`).
***OR***
=> feat: integrate `@qlik/sdk` into mashup template

commands/serve/README.md, commands/serve/lib/init-config.js, commands/serve/lib/serve.js, commands/serve/lib/webpack.serve.js
Serve visualisation bundle to use in microfront end (MFE) environment. The MFE mode is activated with the option `--mfe`.
Example starting Nebula serve in MFE mode:
```sh
nebula serve --mfe
```
This allows visualisation developers to spin up nebula serve, override the import map in the MFE environment (for example QCS) and do development against it. When the source code is changed the bundle is automatically rebuilt.
The MFE mode requires the server to run with HTTPS. This in turn requires certificates to be installed on environment spinning up nebula serve.
**Use option `--systemjs` instead of `--mfe`?**
`--mfe` is intended to describe the purpose for the developer while `--systemjs` is how its technically achieved. For the time being systemjs is the format for the bundle. Later on it …
=> feat(serve): add mfe mode

commands/serve/lib/serve.js, commands/serve/lib/webpack.serve.js
CORS headers needed when serving visualisation artifacts to a MFE environment.
The headers are configured in the options for webpack devserver. These headers are added to responses for requests to `/info` and `/pkg/<name>`.
Question: Would it be useful to allow the headers to be configurable in nebula.config.js?
***OR***
=> fix(serve): add cors headers to `/info` and `/pkg/<name>`

commands/sense/lib/api-entry.js, commands/sense/lib/sense.js
many uses already expect a promise
ex: https://github.com/qlik-oss/sn-scatter-plot/blob/36cf9ce948ac86d9f959f5b9ba62871cf4f065df/scripts/build.js#L39
That use is still OK as the missing promise is only needed when using a external ext file or use a legacy build.
***OR***
=> fix: return promise from cli-sense api

apis/nucleus/src/components/Header.jsx
Modify container styles to apply directly on container element (instead of being applied to sub elements of the container).
Example **without** the fix. Note that there is no padding below the header:
Example **with** the fix. Note the 8px padding below the header:
***OR***
=> fix(nucleus): apply styles on header element

.circleci/config.yml, jest.config.js, package.json, yarn.lock
publishing jest coverage to coveralls.io instead of afterwork
***OR***
=> chore: publish jest coverage to code climate

apis/enigma-mocker/src/__tests__/from-generic-objects.inspect.js, apis/enigma-mocker/src/mocks/get-object-mock.js
Make sure ID and qID are matching when generating generic object mocks.
***OR***
=> fix: correctly check qId in mocker

commands/serve/README.md, commands/serve/lib/serve.js, commands/serve/lib/webpack.serve.js
support for: 
- nebula.config.js file -> `serve: { clientId: <SOME_ID_HERE> }`
- passing `clientId` directly while running `nebula serve  --clientId="<SOME_ID_HERE>"`
This PR depends on: #962 
===
***OR***
=> feat: `clientId` from `nebula.config.js` support

.codesandbox/mekko/sandbox.config.json, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, commands/create/templates/mashup/_package.json, commands/create/templates/sn/none/_package.json, commands/create/templates/sn/picasso/common/_package.json, examples/chart-conversion/package.json, examples/dev-mashup/package.json
=> chore!: set required node version

commands/build/lib/build.js
When you build with `nebula build` and your peer dependency typescript is missing this error message is shown:
`Please install '@rollup/plugin-typescript' to build using typescript.` even though it's installed.
With this change you get the actual error first which is `Cannot find module 'typescript'`
***OR***
=> ci: misleading error message

.github/CONTRIBUTING.md, commands/cli/lib/index.js, commands/cli/package.json, commands/cli/utils/checkNodeVersion.js, commands/create/templates/sn/none/_package.json, commands/create/templates/sn/picasso/common/_package.json, commands/serve/package.json
=> feat: show a message to upgrade node when needed

apis/nucleus/src/components/ActionsToolbarItem.jsx, apis/nucleus/src/components/ActionsToolbarMore.jsx, apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/ListBoxPopover.jsx, apis/nucleus/src/components/listbox/components/ListBoxSearch.jsx, apis/nucleus/src/components/listbox/components/__tests__/list-box-search.inspect.jsx
Issue fixed by this PR:
- Pressing Enter in the search field when there are no matches resets the search and all values, which is not as it should work
Solution:
- Check whether there are hits before accepting them and resetting search
Also fixes a console.error due to `NaN` values in ActionsToolbar.
=> fix(ListBox): accept search results only if there are hits 

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/hooks/useExistingModel.jsx, apis/nucleus/src/components/listbox/hooks/useOnTheFlyModel.jsx, apis/nucleus/src/index.js, apis/stardust/api-spec/spec.json
To be able to set the dense mode from the property panel in sense client, a dense property is added.
This way you also avoid re rendering the Listbox when toggling dense mode, compared to passing dense as an option.
=> feat: add dense as a property

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/__tests__/list-box.test.jsx, apis/nucleus/src/components/listbox/hooks/useExistingModel.jsx, apis/nucleus/src/components/listbox/hooks/useOnTheFlyModel.jsx, apis/nucleus/src/index.js, apis/stardust/api-spec/spec.json
To be able to set the checkboxes and histogram from the property panel in sense client.
=> feat: add checkboxes, histogram as properties

.circleci/config.yml, package.json, yarn.lock
Integration tests started to fail after rendering tests for playwright was added. Probably the playwright install part overwrites some part of the integration tests. (this was however not seen on the local CCI branch?). This PR will move the rendering tests to last in the execution order so that it hopefully does not overwrite anything.
=> test: fixing failing integration test

apis/nucleus/src/utils/__tests__/background-props.test.js, apis/nucleus/src/utils/background-props.js, apis/theme/src/index.js
=> chore: add support for engine ARGB colors

apis/enigma-mocker/index.js, apis/enigma-mocker/package.json, test/mashup/visualize/scenarios.js
Engima mocker had its own build stuff when it isn't needed, I think that messes up the typings.
=> chore: make enigma mocker properly internal

apis/enigma-mocker/README.md
Correct how you import EnigmaMocker in README example.
=> docs: adjust EnigmaMocker path in readme example

apis/nucleus/src/object/__tests__/create-session-object.test.js, apis/nucleus/src/object/create-session-object.js, apis/nucleus/src/sn/__tests__/type.test.js, apis/nucleus/src/sn/type.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, commands/serve/web/components/Visualize/Visualize.jsx
When rendering new object you are forced to specify entire property branches as the initial props are merged, not deeply extended.
=> feat: created object now can extend initial properties

apis/nucleus/src/components/ActionsToolbar.jsx, apis/nucleus/src/components/ActionsToolbarMore.jsx, apis/nucleus/src/components/listbox/ListBoxPortal.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-portal.test.jsx, apis/nucleus/src/hooks/useObjectSelections.js, rollup.config.js
The ... more button in the listbox had broken due to mainly this: https://github.com/qlik-oss/nebula.js/pull/1048/files#diff-bc6a3f095f62f60275871e29a5ac5d22566f2dada32f3e17b897fab53052cdecL56
I also noticed that the contents of it ("select alternatives" etc) wasn't correct, it only used the initial state of the layout. Tried a lot of things to see what was actually wrong, but in the end I just refactored how it sets the actionItems.
=> fix: listbox more menu is broken

apis/nucleus/src/components/ActionsToolbar.jsx, apis/nucleus/src/components/ActionsToolbarMore.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx
To get the look'n'feel back to previous iteration and tidy up the code.
Looks like this now:
Previously:
=> chore: move more popover back into container

apis/nucleus/src/components/listbox/ListBoxInline.jsx
To fix https://github.com/qlik-oss/sn-list-objects/issues/103 by checking selection state and layout.title.
=> fix: do not show Search box on selection when there is no title

apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/index.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
When using search option toggle and the toolbar is hidden, show the search input when entering selection.
This will make the search option `'inSelection'` obsolete.
=> feat(Listbox): remove inSelection search option

apis/nucleus/src/components/listbox/hooks/__tests__/useOnTheFlyModel.test.jsx, apis/nucleus/src/components/listbox/hooks/useOnTheFlyModel.jsx
When mounting multiple listboxes in the same mashup and using the exact same definition, they will also share a model -> meaning they also share the modal selection state.
They should get unique IDs.
=> fix: assign id to all session listboxes

apis/nucleus/src/components/listbox/hooks/__tests__/useOnTheFlyModel.test.jsx, apis/nucleus/src/components/listbox/hooks/useOnTheFlyModel.jsx
When rendering a Listbox on the fly (`embed.field(…).mount()`) and no title is provided in options.
Set a default title.
=> fix(Listbox): use fallback title

apis/nucleus/src/hooks/__tests__/use-app-selections.test.jsx, apis/nucleus/src/hooks/useAppSelections.js
removed to not have react compoents using useAppSelections update on any change in selection
to get the extra information use useAppSelectionsNavigation instead of useAppSelections
from what I can see not be a part of the exposed api
https://github.com/qlik-oss/nebula.js/blob/02441143b8a16475009eabd7f496163042ca98dc/apis/nucleus/src/index.js#L330
found when investigated listbox performance.
see qlik-oss/sn-list-objects#105
fix one source of extra updates but do not have any impact by itself
=> fix: remove broken unused parts of appSelections

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/ListBoxPopover.jsx, apis/nucleus/src/components/listbox/ListBoxPortal.jsx, apis/nucleus/src/components/listbox/__tests__/list-box.test.jsx
the internal logic in useLayout (in useRpc) causes a lot of extra re-rendering of the component using it
(some of the updates are relevant if the request status in the second retrun value is used)
this isolates ListBoxInline and prevent the extra updates from re-rendering it
together with #1117 and #1118 this fixes most (but not all) of the performance problem in qlik-oss/sn-list-objects#105
=> fix: no re-render of inline listbox from extra useLayout updates

apis/nucleus/src/components/listbox/ListBoxInline.jsx
In a filter pane, the action toolbar items (to the right of the header) has 32px height, while the title has 28px height.
This causes the problem reported here https://github.com/qlik-oss/sn-list-objects/issues/119.
To avoid the header height being changed on selection, we set its height to the same height of the action toolbar items.
This PR is to fix https://github.com/qlik-oss/sn-list-objects/issues/119.
=> fix: fix filter pane header change the height on selection

apis/nucleus/src/components/listbox/components/ListBoxRowColumn/ListBoxRowColumn.jsx, apis/nucleus/src/components/listbox/components/ListBoxRowColumn/components/ListBoxRoot.jsx, apis/nucleus/src/components/listbox/components/grid-list-components/item-sizes.js, apis/nucleus/src/components/listbox/hooks/useOnTheFlyModel.jsx
- fixes(https://github.com/qlik-oss/sn-list-objects/issues/121)
- fixes(https://github.com/qlik-oss/sn-list-objects/issues/117)
- fixes "remove borders in histogram mode" (no issue)
- fixes "Leftmost column doesnt have enough padding on the left so the 3 indicators meant to show if it is ordered by row or column (vertical or horizontal) are barely visible here…"
- fixes(https://github.com/qlik-oss/sn-list-objects/issues/90)
Fixes a lot of issues with CSS and gives a much better use of the space, especially in frequency mode (much better than in the existing Filter pane in sense-client).
=> fix: harmonise styles

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/components/grid-list-components/grid-list-components.jsx, apis/nucleus/src/components/listbox/components/grid-list-components/styled-components.js
In edit mode, the search icon should be not shown and scrolling should be disabled (or the scroll bar should not be shown).
This PR is to fix https://github.com/qlik-oss/sn-list-objects/issues/72.
=> fix: hide search icon and scrollbar of a filter pane in edit mode

apis/nucleus/src/components/listbox/components/ListBoxRowColumn/components/FieldWithRanges.jsx
fixes(https://github.com/qlik-oss/sn-list-objects/issues/70)
The algorithm is ok but the `<ValueLabel />` component was not updating due to an incorrect `key`.
=> fix: use a key which triggers update of highlight component

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/__tests__/list-box.test.jsx, apis/nucleus/src/components/listbox/components/grid-list-components/__tests__/__snapshots__/grid-list-components.spec.jsx.snap, apis/nucleus/src/components/listbox/components/grid-list-components/__tests__/grid-list-components.spec.jsx, apis/nucleus/src/components/listbox/components/grid-list-components/grid-list-components.jsx, apis/nucleus/src/components/listbox/hooks/useOnTheFlyModel.jsx
Solves #1120 - rendering of field with `listLayout` option set to `"horizontal"` which has been broken for a while.
This is how it looks like:
Behind the scenes, the option is picked up when rendering a session-based/"one the fly" field and "translated" into the following properties:
```
layoutOptions: {
dataLayout: 'grid',
layoutOrder: 'column',
maxVisibleColumns: { auto: true },
maxVisibleRows: { auto: false, maxRows: 1 }
}
```
=> fix: render listLayout opt properly

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/ListBoxPopover.jsx, apis/nucleus/src/components/listbox/__tests__/list-box.test.jsx, apis/nucleus/src/components/listbox/components/ListBoxSearch.jsx, apis/nucleus/src/components/listbox/components/__tests__/list-box-search.test.jsx, apis/nucleus/src/components/listbox/hooks/selections/__tests__/listbox-selections.test.js, apis/nucleus/src/components/listbox/hooks/selections/__tests__/use-selections-interactions.test.jsx, apis/nucleus/src/components/listbox/hooks/selections/listbox-selections.js, apis/nucleus/src/components/listbox/hooks/selections/selectionState.js, apis/nucleus/src/components/listbox/hooks/selections/useSelectionsInteractions.js, apis/nucleus/src/components/listbox/interactions/listbox-selection-toolbar.js, test/rendering/listbox/listbox.js
Refactor client side selection state to prevent flickering from engine update during selection
select without waiting for previous selection to be done (work for range select as local client state is updated)
(I found one edge case (also in old sense-client listbox) if a failed selection is followed by a working selection (before the response that the first failed) that unnecessary also clear both)
Properly wait for update from onging selection before starting whenthe field is calculated. (before it only waited for the selectListObjectValues to be done not for fetching the new layout/getListObjectData)
=> fix: prevent flickering from engine update during selection

apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/constants.jsx
To fix https://github.com/qlik-oss/sn-list-objects/issues/130 by removing IconButton as a wrapper of DrillDownIcon, so the drill down icon becomes a normal icon which does not have special effect on hovering and clicking like a normal button
=> fix: change drill down icon from button icon to a normal icon

apis/nucleus/src/components/listbox/hooks/selections/useSelectionsInteractions.js
fix removeListener call 'deactivated' not 'activated'
add extra event ('clearItemStates') for use in direct query use case in sense-client 
(when sense client selection toolbar and not the nebula one is used)
=> fix: remove correct listener & add extra event

apis/locale/locales/de.json, apis/locale/locales/en-US.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json, apis/nucleus/src/components/listbox/ListBoxInline.jsx
Add a tooltip for the lock button in listbox inline
Resolves https://github.com/qlik-oss/sn-list-objects/issues/93
=> fix: add tooltip lock button

apis/nucleus/src/components/listbox/ListBoxInline.jsx
Currently if the listbox has no title, the search box will be shown on selection activated. However, search box should only be shown if the user clicks the search icon, otherwise it should not be shown.
This is to fix https://github.com/qlik-oss/sn-list-objects/issues/181.
=> fix: do not show search box on selection

apis/nucleus/src/components/listbox/ListBoxInline.jsx
This is to fix https://github.com/qlik-oss/sn-list-objects/issues/183 and also make search icon and lock icon more readable when it is disabled.
=> fix: show search icon in edit mode if the search checkbox is on

apis/nucleus/src/components/ActionsToolbarItem.jsx, apis/nucleus/src/components/listbox/components/ListBoxRowColumn/ListBoxRowColumn.jsx
Adds data-testid for buttons in ActionToolbar:
* `actions-toolbar-cancel`
* `actions-toolbar-confirm`
* ...
Also adds `data-testid="listbox.item"` for listbox items in the listbox.
=> test: add test-ids for testing

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/__tests__/cell.test.jsx
When rendering an existing chart using a generic load function, the chart would fail to render due to it being not registerd.
Sample setup:
```
{
const nebbie = nebula.embed({
context: {
language: 'en-US',
constraints: {
select: false,
passive: false,
active: false,
},
theme: 'light',
},
load: ({ name, version }) => {
if (name === 'barchart' || name === 'bar') {
return Promise.resolve(bar);
}
}
});
nebbie.render({
id: "lnjsg"
});
```
This change removes a check in Cell.jsx that stopped us getting to the generic load function. That error is now removed and replaced by a dev warning.
=> fix: generic load function should work for existing charts

apis/nucleus/src/object/__tests__/populator.test.js, apis/nucleus/src/object/populator.js
embed.render(..) session objects didn't work for objects using /qListObjectDef as data path, this fixes that.
=> feat: support listobjectDef in render session objects

apis/nucleus/src/components/listbox/components/ListBoxSearch.jsx
Adds data-testid="search-input-field" for search input for the listbox to allow for better auto-testing.
=> test: add data-testid for search input field

apis/nucleus/src/components/ActionsToolbar.jsx
Moves the ActionToolbar slightly again to mitigate problem with overlapping of values.
Before:
After:
=> refactor: adjust action toolbar position

apis/nucleus/src/components/listbox/components/ScreenReaders.jsx
ignores `ScreenReaderForSelections` so that it doesn't end up in the api specs.
=> docs: ignore jsdoc for internal fn that is not part of api

apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/interactions/__tests__/list-box-keyboard-navigation.test.js, apis/nucleus/src/components/listbox/interactions/listbox-keyboard-navigation.js
remove focus listbox on hover
and move the logic to global keydown to still work
=> fix: leave focus unchanged on hover

apis/nucleus/package.json, apis/stardust/package.json, yarn.lock
There is a problem of a popover width calculation caused by "react-virtualized-auto-sizer" ^1.0.11. Changing "react-virtualized-auto-sizer" to 1.0.7 to solve this problem.
=> fix: change react-virtualized-auto-sizer to 1.0.7 to fix width problem

apis/nucleus/src/index.js, apis/nucleus/src/object/__tests__/create-object.test.js, apis/nucleus/src/object/create-object.js, apis/nucleus/src/object/create-session-object.js, apis/nucleus/src/object/get-generic-object.js, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/supernova/src/hooks.js, commands/serve/web/eRender.html
Adds new APIs to better support creating new charts outside of Nebula:
- embed.create: Allows creating a new engine object OR getting the property structure for one
- ~useEmitter: Allows a chart to communicate with the outside~: now in separate PR: #1168 
=> feat: create api

apis/nucleus/src/components/ActionsToolbarItem.jsx, apis/nucleus/src/components/ActionsToolbarMore.jsx, apis/nucleus/src/components/__tests__/actions-toolbar-item.test.jsx, apis/nucleus/src/hooks/useDefaultSelectionActions.js
=> fix: make spacebar work on all buttons in action toolbar

apis/nucleus/src/components/listbox/components/ListBoxSearch.jsx, apis/nucleus/src/components/listbox/components/useTempKeyboard.js, apis/nucleus/src/components/listbox/interactions/listbox-keyboard-navigation.js
To fix https://github.com/qlik-oss/sn-list-objects/issues/263.
The user should be able to go from a folded listbox to the first row by Enter like an unfolded listbox.
=> fix: support Enter to go from a folded listbox to a row

commands/build/lib/build.js, commands/build/lib/config.js, commands/build/lib/init-config.js, commands/build/lib/systemjs.js, commands/build/lib/watch.js
it takes too much time to build an extension using nebula build
Add systems into config to be able to disable systemjs build
```
systemjs: {
description: 'Enable to transpile a systemjs format for release',
type: 'boolean',
default: true,
},
```
`argv.systemjs && (await systemjs(buildConfig));`
https://github.com/qlik-oss/sn-table/pull/991 
Refactoring build/lib to separate related functions to its own file
=> feat: to be able to disable systemjs in build

apis/nucleus/src/components/listbox/components/ListBoxRowColumn/ListBoxRowColumn.jsx, apis/nucleus/src/components/listbox/components/ListBoxRowColumn/__tests__/list-box-row-column.test.jsx, apis/nucleus/src/components/listbox/interactions/keyboard-navigation/__tests__/find-next-item-index.test.js, apis/nucleus/src/components/listbox/interactions/keyboard-navigation/__tests__/keyboard-nav-rows.test.js, apis/nucleus/src/components/listbox/interactions/keyboard-navigation/find-next-item-index.js, apis/nucleus/src/components/listbox/interactions/keyboard-navigation/keyboard-nav-rows.js
To fix https://github.com/qlik-oss/sn-list-objects/issues/277.
=> fix: support keyboard navigation (arrow key up/down) in grid mode

apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-inline.test.jsx, apis/nucleus/src/components/listbox/interactions/__tests__/listbox-show-toolbar-detached.test.js, apis/nucleus/src/components/listbox/interactions/listbox-show-toolbar-detached.js
Detach toolbar on resize.
fixes https://github.com/qlik-oss/sn-list-objects/issues/244
Before:
After:
=> fix(listbox): detach toolbar on resize

apis/nucleus/src/utils/background-props.js
When rendering snapshots there is no app to get the url from. Chart monitoring in hub is using snapshots. It would create the image urls in the following way:
`baseUrl/undefined/api/v1/.....`
This will make sure the url will at least be:
`baseUrl/api/v1/.....`
But will only fix requests from the same domain
=> fix: resolve server url to empty string

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/__tests__/list-box.test.jsx
Only show "No matches for your search" disclaimer when qCardinal is > 0.
Also trigger `renderedCallback?.()` when qCardinal is 0.
fixes https://github.com/qlik-oss/sn-list-objects/issues/293
fixes https://github.com/qlik-oss/sn-list-objects/issues/269
=> fix: take empty field into account

commands/serve/web/components/Visualize/Visualize.jsx, commands/serve/web/eRender.js, commands/serve/web/hot.js
Fixes so that serve awaits added types before running.
=> fix: correctly await types in serve

apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/supernova/src/hooks.js, commands/serve/web/render-fixture.js
Event emitter didn't actually have an off function, so switching to add/remove instead.
=> fix: correct usage of event-emitter

apis/locale/src/translator.js, apis/nucleus/src/hooks/useObjectSelections.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/supernova/src/hooks.js, apis/theme/src/index.js
We have some missing types requirement from some of the startdust APIs listed below: 
1. `stardust.ObjectSelections`
2. `stardust.Translator`
3. `stardust.Theme`
4. `stardust.keyboard`
for first 3, we were extending the stardust interface in our side [like this](https://github.com/qlik-oss/sn-table/blob/0ac826331ff9b64804f7e128043726f70ea8c481/src/types.ts#L173-L185).
but for last one (`stardust.keyboard`), we were using `@ts-ignore` for functions like: 
1. `keyboard.blur(...)`
2. `keyboard.focusSelection(...)`
because those functions does not accept any parameter by **types** (which they do in code [at here for focus selection](https://github.com/qlik-oss/nebula.js/blob/64a3b201dd9938a94765a4948230b3a8e7337624/apis/supernova/src/hooks.js#L1131) and [here for …
=> fix(type): add missing type info required by `sn-table`

commands/build/README.md, commands/build/lib/config.js, commands/build/lib/init-config.js
In some scenarios, integrating third-party packages require no source maps, browser to be set to true and preferBuiltins set to false.
This PR creates the following flags
- disableSourceMaps; will prevent the sourcemaps from being generated
- browser; boolean
- preferBuiltins; boolean
=> feat: add browser, and preferBuiltins cli args

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/sn/__tests__/types.test.js, apis/nucleus/src/sn/types.js
When rendering a sheet (or multiple charts) of an un-supported type Nebula would crash instead of just showing a warning. This was due to a missmatch between a null version and undefined version.
Also fixed the rendering of the footer to be hidden when the chart fails to load.
=> fix: do not crash on unknown chart + footer

apis/nucleus/src/__tests__/viz.test.js, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/supernova/src/hooks.js
Exposes the Imperative handle API in the form of
- useImperativeHandle component hook
- getimperativeHandle viz API function
=> feat: add Imperaitive Handle to public API

.circleci/config.yml
=> chore: make api-governance job depend on build

apis/stardust/api-spec/listbox-spec.conf.js, apis/stardust/api-spec/listbox-spec.json
Make the Listbox api public on qlik.dev
Current look on internal: https://internal.qlik.dev/apis/javascript/nebulajsstardustlistbox
=> chore: make listbox api public

apis/nucleus/src/components/listbox/ListBoxPopover.jsx, apis/nucleus/src/components/listbox/assets/list-sizes/use-list-sizes.js
The popover listbox was failing since the listbox assumed that theme existed. Both passing it from the popover and adding a sanity check. We probably need a component test for the popover or type some of the props so this would have been discovered before releasing
=> fix: pass theme to listbox

commands/build/lib/watch.js
Issue with the build watcher when running --mfe
=> fix: missing path require in build-watcher

apis/nucleus/src/components/selections/SelectedFields.jsx, apis/nucleus/src/components/selections/__tests__/selected-fields.test.jsx, apis/nucleus/src/hooks/__tests__/use-app-selections.test.jsx, apis/nucleus/src/hooks/__tests__/use-object-selections.test.jsx, apis/nucleus/src/hooks/useAppSelections.js, apis/nucleus/src/hooks/useObjectSelections.js, apis/nucleus/src/stores/selections-store.js
If there is a master filterpane and few collapsed filterpane objects are based on this master item, then everytime the user select an item in the listbox popover from a collapsed filterpane the listbox popover will be closed right away.
The problem is that currently we use one object selection for all filterpanes with the same model and then we check if a click is outside a filterpane or not and if it is then we trigger deactivated event which will close the listbox popover.
=> fix: fix selection close when there are many objects with the same model

README.md
Repair broken link to stardust readme from main readme.
=> docs: fix links to stardust in readme

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/components/ListBoxDisclaimer.jsx, apis/nucleus/src/components/listbox/components/ListBoxError.jsx, apis/nucleus/src/components/listbox/components/ScreenReaders.jsx, apis/nucleus/src/sn/__tests__/type.test.js, apis/nucleus/src/sn/type.js, commands/build/lib/build.js, commands/build/lib/resolveNative.js, commands/build/lib/watch.js, commands/cli/lib/index.js, commands/create/lib/create.js, commands/create/templates/sn/picasso/common/src/pic-selections.js, commands/sense/lib/build.js, commands/serve/lib/fixtures.js, commands/serve/lib/placeholder.js, commands/serve/lib/webpack.serve.js, commands/serve/web/components/Visualize/Visualize.jsx, rollup.config.js
=> chore: clean warnings in build

apis/enigma-mocker/src/from-generic-objects.js, apis/nucleus/src/hooks/__tests__/use-rpc.test.jsx, apis/nucleus/src/hooks/useRpc.js
Solves a race condition that has occurred a couple of times when rendering charts using a mocked data model (no real engine), both when using EnigmaMocker and when "manually" mocking the engima app model.
I have no really good explanation to exactly how this solves the problem, but it does. And I see no big risk in introducing this extra await with the setTimeout into `useRpc`, since all of those backend calls are asynchronous anyway - they will always have some kind of delay in real life scenarios.
TODO:
=> fix: race condition for mocked charts

apis/nucleus/src/components/listbox/ListBoxInline.jsx
When a listbox row get focus, screen reader user should be informed that content on the page can change when row is  activated.
fixes https://jira.qlikdev.com/browse/QB-19506
=> fix: move listbox screen reader instruction to aria-label

apis/conversion/src/index.js, apis/nucleus/src/__tests__/viz.test.js, apis/nucleus/src/index.js, apis/nucleus/src/utils/can-set-properties.js, apis/nucleus/src/utils/save-soft-properties.js, apis/nucleus/src/utils/set-properties.js, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/supernova/src/index.js
I decided to make this simpler for now just add a parameter to the current api to support patching and keep the new API hidden.
=> feat: object conversion for readonly charts (#1335)

commands/build/lib/watch.js
Extends #1349 to also include when building using the watch flag
=> feat: supress "use client" warnings in charts build with watch flag

apis/nucleus/src/components/listbox/assets/list-sizes/column-mode.js, apis/nucleus/src/components/listbox/assets/list-sizes/row-mode.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
Division by 0 lead to `columnCount == Infinity`.
Force `rowCount` or `columnCount` to be at least 1.
=> fix: prevent only one item rendering in single grid mode

apis/nucleus/src/hooks/__tests__/use-session-model.test.jsx, apis/nucleus/src/hooks/useSessionModel.js
Fixes an issue where the alternate states wasn't displayed at all in current selections. 
Instead of using a shared model there where two current-selections session objects, with only one getting the alternate states patch. This looks to be due to a timing issue where the two calls to useCurrentSelectionsModel was done too close to eachother thus not having time to store the rpcCall. This change introduces a sync storage of the call promise instead of waiting fo the actual call to be made.
=> fix: handle sync calls to session storage

apis/nucleus/src/components/listbox/assets/__tests__/styling.test.js, apis/nucleus/src/components/listbox/assets/styling.js, apis/stardust/api-spec/spec.json
The mui function `getContrastRatio` does not support named colors ('red', 'transparent' etc.) and will throw an error if sent in. Therefore, we must convert these colors first and as an extra safety net, wrap the function in a try-catch to be sure to prevent misspelled colors from throwing an error.
Note! This issue blocks the nebula release and bump.
Selections are possible and do not throw.
https://github.com/qlik-oss/nebula.js/assets/5780544/2622b808-5993-4285-aea3-a4422840c4cb
I have also tried to change styling and themes etc.
=> fix: handle unsupported colors and add tests

apis/nucleus/src/utils/color/color.js, apis/nucleus/src/utils/style/shadow-utils.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
Removes the utility function `getFullBoxShadow` from the api spec (was accidentally included in the last nebula version).
=> docs: remove internal fn from api spec

apis/nucleus/src/components/listbox/assets/__tests__/styling.test.js, apis/nucleus/src/utils/style/styling-props.js, test/rendering/listbox/__fixtures__/multi_scenario_list_1_bgimage.js
Remove support for alternative naming of properties, e.g. seen in the ActionButton repo, as it is just adding confusion.
=> fix(listbox): conform to previous background image properties naming

apis/nucleus/src/utils/style/__tests__/styling-props.test.js, apis/nucleus/src/utils/style/styling-props.js
In Sense you can set a background per chart using the Styling panel and General tab, there you can set the background to "color by expression". When setting a color by expression via the Styling panel, `useColorExpression` is set as a property in indicate that the color expression should be used.
Not really sure what is the single source of truth here but I'm assuming charts have been using that panel to set the background, which means there are charts in the wild using `useColorExpression`.
=> fix: bgColor with useColorExpression property

apis/theme/src/themes/base.json
To align with the design for most of our sn charts, the default font size should be 12px
=> fix: use 12px as default font size in theme

apis/nucleus/src/components/listbox/hooks/__tests__/useExistingModel.test.jsx, apis/nucleus/src/components/listbox/hooks/useExistingModel.jsx
It was noticed that layout changes did not trigger the useEffect in `ListBoxInline.jsx`. After some investigation help from @T-Wizard it was found that this was caused by the session model not being stored in Nebula's model store. This in turn lead to the fetch layout call never being performed and the useEffect callback not being called.
The useEffect callback should always be called when layout changes (in this case, tested with `qLocked` state).
With this PR, the session model is *always* stored. The code was also refactored to reduce duplication of code logic.
=> fix: always store session model (also when not fetching it)

commands/serve/lib/webpack.serve.js
Fixes the displayed URL to actually work for the override when it contains illegal URL characters such as @ and / 
=> fix: display correct override URL

apis/supernova/src/hooks.js
Limit the use contraints deprecation warning to once per component per session as it can be spammy.
=> chore: limit contraints warnings to once per component per session

apis/nucleus/src/components/listbox/components/ListBoxRowColumn/__tests__/list-box-radio-button.test.jsx, apis/nucleus/src/components/listbox/components/ListBoxRowColumn/components/CheckboxField.jsx, apis/nucleus/src/components/listbox/components/ListBoxRowColumn/components/ListBoxRadioButton.jsx
Radio buttons do not pick up the selected color.
Apply `styles.selections.selected` on checked radio buttons.
Also, apply `styles.content.color` for unselected boxes to allow for customisation of unselected radio buttons through the theme (allowing for customisation through the selection state color, such as excluded or possible, might just add confusion and look bad in some cases).
=> fix(listbox): color radio buttons with custom styling

apis/theme/src/__tests__/palette-resolver.test.js, apis/theme/src/palette-resolver.js
When an invalid color is sent in to the `uiColor` resolver function, it starts digging into the object without sanity checking it first. This throws an error that causes the listbox not to render in some cases. It can also be reproduced by resetting background styling.
This PR adds a sanity check, that checks for the existence of either `index` or `color` on the object (one of them is required to exist). This solves the problem in mentioned cases.
=> fix: sanity check color input in uiColor resolver

apis/nucleus/src/components/listbox/components/ListBoxSearch.jsx, apis/nucleus/src/components/listbox/components/__tests__/list-box-search.test.jsx
There is a limitation in how many characters we should allow users to search for. This limitation existed in the old Listbox in sense-client but has so far not been added to the new Listbox.
=> fix(Listbox): Limit search length to 64000 characters

apis/nucleus/src/components/listbox/ListBoxPopover.jsx, apis/nucleus/src/components/listbox/components/ListBoxSearch.jsx, apis/nucleus/src/components/listbox/interactions/keyboard-navigation/keyboard-nav-rows.js
**Issue:**
Pressing Enter key after making some selections via straight table search box, does not close the search listbox.
**Solution:**
Being sure that `EnterKey` confirms the selection and "return" the event to avoid stopPropagation()
In this video I clicked Enter to confirm and close the listbox.
https://github.com/qlik-oss/nebula.js/assets/20701546/05d08d82-fe52-4ad0-ab6e-9af5bfd35c14
=> fix(QB-25634): press Enter key does not close listbox

apis/nucleus/src/components/listbox/interactions/keyboard-navigation/__tests__/keyboard-nav-container.test.js, apis/nucleus/src/components/listbox/interactions/keyboard-navigation/keyboard-nav-container.js
To fix https://jira.qlikdev.com/browse/QB-25773.
The problem is that after entering the listbox and then open the search box, hover.current is still true.
To solve the problem either we need to set hover.current to false on the search box being opened, or in globalKeyDown we need to check if the search box is opened or not.
=> fix: avoid triggering scroll on search box open

apis/nucleus/src/components/listbox/assets/__tests__/styling.test.js, apis/nucleus/src/components/listbox/assets/styling.js
I'm working on adding theme support for selection colors in listbox.
Given that there will be even more logic to get the correct background and font colors, I have "prefactored" the logic to be more general. All 5 different selection states maps really well to the prop names on sprout, the layout, and the theme (except for palette.selected.main...) 
To me this is as readable as before, but more compact and easier to change the logic later.
=> refactor: generalize selection styling logic

apis/nucleus/src/components/listbox/ListBoxInline.jsx
Recover the old behaviour of expanded listbox. Opening search input in expanded listbox should also activate selection mode.
=> fix: activate selection mode on show search input for expanded listbox

apis/nucleus/src/components/listbox/ListBoxInline.jsx
in this [PR](0dea433ef1a3ee135d74f78f253904aaa7bf8fbf) the selection mode is activated eventhough `selectionState.selectionDisabled` is true.  
=> fix: should not activate selection when selectDisabled is true

apis/nucleus/src/components/listbox/ListBoxPopover.jsx, apis/nucleus/src/components/listbox/interactions/keyboard-navigation/keyboard-nav-rows.js
With this fix, it is possible to navigate through the listbox by TAB key when the popover list box is open on the other chart than filterpane. Multiple tabbing moves the tab to the confirmation button and returns it to the searchbox.
https://github.com/user-attachments/assets/3f7b05f2-089f-49d6-b967-e32064d6028d
=> fix(QB-27479): Tab key navigation on popover listbox

yarn.lock
Generation of Type Definitions stopped working properly, for some reason, after updates to `yarn.lock` in #1564. I'm not entirely sure why `yarn.lock` was updated in that PR, but I see no reason for it, so to get things working properly again I'm reverting these changes.
=> chore: revert unwanted changes to yarn.lock

apis/nucleus/src/components/ActionsToolbarMore.jsx
prevent menu from being under other thing (ex: objects)
partly undo #1090 (move more popover back into container)
but the menu aligment form that was already broken (I think from #1123, but that is not verified)
without fix
with fix
=> fix: move more menu out of container

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/Sheet.jsx, apis/nucleus/src/components/glue.jsx, apis/nucleus/src/components/sheetGlue.jsx, apis/nucleus/src/index.js, apis/nucleus/src/object/__tests__/create-session-object.test.js, apis/nucleus/src/object/__tests__/initiate.test.js, apis/nucleus/src/object/create-session-object.js, apis/nucleus/src/object/get-generic-object.js, apis/nucleus/src/object/initiate-sheet.js, apis/nucleus/src/object/initiate.js, apis/nucleus/src/object/navigation/navigation.js, apis/nucleus/src/sheet.js, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/stardust/src/index.js, apis/stardust/types/index.d.ts, apis/supernova/src/creator.js, apis/supernova/src/hooks.js, apis/supernova/src/index.js
This PR is to add sheet navigation capability to support using sn-nav-menu in a mashup using qlik-embed to embed a sheet. The main idea is to create a navigation api for each sheet rendering to avoid the case when there are more than one sheet is rendered.
The navigation api needs to know the sheet to update the sheet based on new sheet ID.
The navigation api is passed to each chart context.
https://github.com/user-attachments/assets/e29414c0-3cba-48e5-86f1-6bc9d261c5d9
=> feat: add sheet navigation

apis/nucleus/src/components/listbox/ListBoxPopover.jsx, apis/nucleus/src/components/listbox/ListBoxPopoverWrapper.jsx
Adds the ability to customize the sort order for a field in the listbox popover. It is needed in the "Sorting in search" feature in the pivot table, as that requires the sort order for the field in the listbox to match that of the dimension in the pivot table.
I could not find any test for the listbox popover, so no tests added either.
=> feat: listbox popover sorting option

apis/nucleus/src/components/ActionsToolbarMore.jsx
Reverting this fix https://github.com/qlik-oss/nebula.js/pull/1568.
It introduces a bigger problem for some use-cases, where clicking the menu is considered a click outside for the listbox popover, causing it to close. So for now we will have to reintroduce the overlap issue.
=> fix: disable portal for actions toolbar more menu

apis/nucleus/src/components/selections/OneField.jsx
Show user-created labels from
master dimensions as labels in
the Nebula  selection bar, when
available.
=> feat: dimension labels in selection bar

commands/serve/lib/webpack.serve.js, commands/serve/web/render-fixture.js
Support passing 'anything' object through nebula serve by adding it in nebula.config.js file. This is to help rendering tests which is run by using nebula serve.
=> chore: support 'anything' through nebula serve

apis/nucleus/src/__tests__/nucleus.test.js, apis/nucleus/src/index.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, commands/build/lib/systemjs.js
Adds the possibility to pass a hostConfig into Nebula, making it available on the Galaxy env parameter for use in charts.
=> feat: add host config to config and galaxy

commands/build/lib/config.js, commands/build/lib/init-config.js
Browser should be the default target of the nebula build, but it turned out to be set to false.
Also fixes regex imports for default externals for core builds
=> fix: make browser the default target

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/glue.jsx, apis/nucleus/src/object/create-session-object.js, apis/nucleus/src/object/get-generic-object.js, apis/nucleus/src/object/initiate.js, apis/nucleus/src/sn/load.js, apis/nucleus/src/utils/render-error.js, apis/nucleus/src/utils/visualization-error.js, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, test/mashup/visualize/life.html, test/mashup/visualize/life.int.js, test/mashup/visualize/scenarios.js
Adds on error and on render callbacks to the nebbie.render call.
Exposes internal render errors as RenderError + originalError
Original motivation is to make it easier for QlikEmbed to be debugged as currently any error during the loading process of the chart is just swallowed. Only tested initially with those types of errors, but could be expanded to let charts expose their own error handling as well.
=> feat: add onError and onRender callbacks

apis/stardust/src/index.js, apis/supernova/src/index.js
Expose `useRef` so it can be imported using `import { useRef } from "@nebula.js/stardust";`
=> fix: expose useRef

apis/nucleus/src/components/listbox/ListBoxPortal.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-portal.test.jsx, apis/nucleus/src/index.js
add method for updating options on a listbox/field similar to already existing method on viz
to be used in filter pane to update components options (styling) when changed (without delete and create a new listbox)
=> feat: update listbox options

commands/build/lib/config.js, commands/build/package.json, yarn.lock
Fixes #1471 , the issue where the `watch` flag in the `build` command does not pick up file changes. This also includes the `serve` command since it's using the same underlying code.
The root cause of this issue seem to be that the `rollup-plugin-sourcemaps` plugin has not updated to support Rollup v4, which has some changes to it's Plugin API (https://rollupjs.org/migration/#changes-to-the-plugin-api).
From the tests I've done Babel source maps works fine as a replacement.
There still seem to be some issue related to `@rollup/plugin-commonjs ` where it can crash the build/watch process. But I'm not able to reproduce that consistently across the different nebula.js projects I've tested with. But this PR https://github.com/rollup/plugins/pull/1639 seem to be the culprint of that crash at …
=> fix: watch using rollup v4

apis/nucleus/src/components/listbox/ListBoxPopover.jsx, apis/nucleus/src/components/listbox/ListBoxPopoverWrapper.jsx
In this PR:
Regarding RTL improvement in sn-table, menu-list-search components should be reversed in RTL mode. To do so, direction as a new property has been added to ListboxPopover and the inner children such as Listbox.
The related PR in nebula-table can be found here: https://github.com/qlik-trial/nebula-tables/pull/897 
Feature Flag: CLIENT_IM_7150_TABLE_RTL. I have passed direction there to the Listboxpopover and without giving reference to that PR, you can't see the changes, so I attached a video to show how menu components are supposed to behave in RTL mode.
https://github.com/user-attachments/assets/6cf82793-9b1c-4378-9fa9-3bbe1c04e578
=> feat: add direction to listboxPopover properties

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/Sheet.jsx, apis/nucleus/src/utils/__tests__/cell-padding.test.js, apis/nucleus/src/utils/cell-padding.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
when feature flag (VNA-13_CELLPADDING_FROM_THEME) is on set cell padding depending on if the sense theme is card or not. and add footer divider for card themes
=> feat: cell spacing based on theme

apis/nucleus/src/components/listbox/assets/styling.js, apis/nucleus/src/utils/style/__tests__/resolve-color.test.js, apis/nucleus/src/utils/style/resolve-color.js, apis/nucleus/src/utils/style/styling-props.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/theme/src/__tests__/palette-resolver.test.js, apis/theme/src/index.js, apis/theme/src/palette-resolver.js, test/component/hooks/hooks.comp.cjs
Alings the functionality around "none" colors in palettes to how it is handled else in Qlik, to make sure colors are resolved correctly for embedded charts.
It removes the supportNone parameter from the API, but it should no longer be needed.
=> fix: align theme none color to client

apis/supernova/src/generator.js
Exposes the EXT object on generator to allow for better extension loading.
=> feat: expose ext on generator

apis/nucleus/src/components/Header.jsx
Previously selection toolbar is inline with title when
- Has chart title or chart subtitle
- and chart width is more than 221 px
Which causing chart area jumping when enter and exit selection mode. Original implementation PR https://github.com/qlik-oss/nebula.js/pull/401.
The fix is detaching selection toolbar from title, always show as a popover. Also make it as same behaviour with classic chart in sense client. (The selection popover top position is slightly different than classic chart selection popover, I think is acceptable).
Tested header of listbox works as before, didn't affected by this change.
**Before fix nebula chart:**
https://github.com/user-attachments/assets/cb0226f2-6f3d-456a-aed4-c721acc92b71
**After fix nebula chart:** …
=> fix: detach selection toolbar from title

apis/nucleus/src/components/listbox/components/ListBoxDisclaimer.jsx
This PR fixes this internally reported bug. In short, the bug description is that the listbox disclaimer text gets cropped in selections tool. The videos shows before and after the fix. 
Before: 
https://github.com/user-attachments/assets/370ffe48-1b0b-4d14-b7ef-d2e4b9eb8761
After: 
https://github.com/user-attachments/assets/1789de9f-2b0a-4537-8edd-ad7236f20c4b
=> fix: cropped text issue in listbox disclaimer

apis/nucleus/src/__tests__/nucleus.test.js, apis/nucleus/src/__tests__/viz.test.js, apis/nucleus/src/index.js, apis/nucleus/src/utils/escape-field.js, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
Adds theme to the galaxy env which means we can get the same setup for property panel def in and out of client.
Adds getPropertyPanelDefinition to new viz APis.
=> feat: add theme to galaxy and getPropertyPanelDefinition to viz

apis/nucleus/src/hooks/useLayout.js
Due to a change in how the useLayout timing works we get some issues with the ListboxPopover. By checking that we actually get a layout back first we can ensure that the timing is the same and that the data is up to date.
=> fix: make layout timing match old setup

apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
Adds correct return type to viz.destroy
=> fix: add return type for viz.destroy

apis/enigma-mocker/src/__tests__/from-generic-objects.test.js, apis/enigma-mocker/src/from-generic-objects.js
Makes it possible to provide a mocked response for `getListObject` when using enigma-mocker through nebula serve.
Instead of always resolving an empty promise it now looks in the list of provided genericObject mocks and returns the corresponding one if provided.
=> feat: allow mocking of getListObject

apis/nucleus/src/components/NebulaApp.jsx, apis/nucleus/src/components/glue.jsx
Makes sure a new render gets an error if the Nebula instance was destroyed before it could finish
=> fix: stop rendering if destroyed

apis/conversion/src/array-util.js, apis/supernova/src/handler/__tests__/data-property-handler.test.js, apis/supernova/src/handler/__tests__/hypercube-handler.test.js, apis/supernova/src/handler/data-property-handler.js, apis/supernova/src/handler/hypercube-handler.js, apis/supernova/src/handler/utils/hypercube-helper/__tests__/hypercube-utils.test.js, apis/supernova/src/handler/utils/hypercube-helper/__tests__/reinsert-main-dimension.test.js, apis/supernova/src/handler/utils/hypercube-helper/__tests__/reinsert-main-measure.test.js, apis/supernova/src/handler/utils/hypercube-helper/hypercube-utils.js, apis/supernova/src/handler/utils/hypercube-helper/reinsert-main-dimension.js, apis/supernova/src/handler/utils/hypercube-helper/reinsert-main-measure.js
Moving generic hypercube functions from sense-client to nebula.js - PART04
In this PR the functions that are required to move, replace and reinsert fields and alternative fields, are considered.
The source files for these functions are in sense-client (data-property-handler.ts & hypercube-handler.js)
P.S: Other parts of this task can be found here: 
[Part01](https://github.com/qlik-oss/nebula.js/pull/1716) ✅ 
[Part02](https://github.com/qlik-oss/nebula.js/pull/1715) ✅ 
[Part03](https://github.com/qlik-oss/nebula.js/pull/1729) ✅
=> chore: add hypercube generic functions - part04

apis/nucleus/src/index.js
Set navigation default value to `undefined` instead of `{}`.
=> fix: change default navigation value to undefined
