qlik-oss/nebula.js

test/e2e-cli/sn.spec.js, test/integration/setup.spec.js, test/integration/sn.spec.js
=> test: increase timeout

.circleci/config.yml, packages/create/generator/templates/project/picasso/barchart/test/integration/interaction.spec.js
=> test(cli-create): ci test generated barchart

.circleci/config.yml, packages/create/generator/templates/project/none/_package.json, packages/create/generator/templates/project/none/test/integration/hello.spec.js, packages/create/generator/templates/project/none/test/integration/setup.spec.js
Include basic integration test for simple supernova template
=> test(cli-create): generate integration test for basic supernova

.circleci/config.yml, package.json, packages/create/templates/picasso/barchart/test/integration/interaction.spec.js
Need to run cli based on current commit to validate the current code base.
=> ci: run barchart generator from current commit

packages/nucleus/src/object/hc-handler.js, packages/serve/web/components/FieldsPopover.jsx, packages/serve/web/components/property-panel/Fields.jsx, packages/serve/web/components/property-panel/HyperCube.jsx, packages/serve/web/hooks/useLibraryList.js
Adds support for library fields (dimension, measures) in the add data dropdown.
=> feat(cli-serve): add support for library fields

packages/nucleus/__tests__/unit/object-api.spec.js, packages/nucleus/package.json, packages/nucleus/src/index.js, packages/nucleus/src/object/create-object.js, packages/nucleus/src/object/object-api.js, packages/nucleus/src/sn/__tests__/type.spec.js, packages/nucleus/src/sn/__tests__/types.spec.js, packages/nucleus/src/sn/load.js, packages/nucleus/src/sn/type.js, packages/nucleus/src/sn/types.js, packages/serve/web/components/App.jsx
Implements basic versioning of object properties and supernovae.
Relates to #39
=> feat(nucleus): basic type versioning

rollup.config.js
Transpile `supernova` to make it work in IE11
=> fix: transpile supernova

commands/serve/command.js, commands/serve/lib/engine.js, commands/serve/lib/serve.js, commands/serve/package.json
Remove unnecessary `execa` dependency
Add `ACCEPT_EULA` in `serve` command with `-a` alias
=> fix: ensure gracefully docker start and stop

apis/nucleus/__tests__/unit/header.spec.jsx, apis/nucleus/__tests__/unit/selectiontoolbar.spec.jsx, apis/nucleus/src/components/Header.jsx, apis/nucleus/src/components/SelectionToolbar.jsx
Make the selection toolbar more generic and not tightly coupled to a supernova
=> refactor(nucleus): selection toolbar

commands/sense/README.md, commands/sense/command.js, commands/sense/lib/build.js, package.json
When developing an extension, it would be nice to output the extension directory into a specific folder to save time. 😃
=> feat: add output directory arg to sense command

commands/serve/lib/webpack.build.js
Add better support for local `nebula.js` development
=> build: use alias for local nebula.js dev

apis/nucleus/src/components/listbox/ListBoxPopover.jsx
Ensure better listbox definition e.g sorting
=> fix: listbox def

commands/serve/web/components/App.jsx, commands/serve/web/eDev.html, packages/ui/components/index.js, packages/ui/icons/SvgIcon.jsx
Add possibility to toggle direction e.g `ltr` `rtl`.
=> feat: add toggle direction

apis/nucleus/package.json, apis/nucleus/spec/spec.conf.js, apis/nucleus/spec/spec.json, apis/nucleus/src/index.js, apis/nucleus/src/object/create-object.js, apis/nucleus/src/object/get-object.js, apis/nucleus/src/selections/app-selections.js, apis/nucleus/src/sn/load.js, apis/nucleus/src/sn/type.js, apis/nucleus/src/viz.js, package.json, yarn.lock
=> docs: add initial spec

commands/serve/command.js, commands/serve/lib/serve.js, commands/serve/lib/webpack.serve.js, commands/serve/web/connect.js
Support running against an Elastic backend e.g `QCS` `QSEoK`
=> feat: support elastic backend

apis/nucleus/src/index.js, apis/nucleus/src/sn/types.js
Provide `nucleus` in `env` to enable rendering objects within objects
=> feat(supernova): provide nucleus in env

commands/serve/lib/snapshot.js, commands/serve/lib/webpack.serve.js, commands/serve/package.json, commands/serve/web/components/Cell.jsx, commands/serve/web/components/Chart.jsx, commands/serve/web/eRender.html, commands/serve/web/eRender.js, packages/ui/components/index.js, yarn.lock
Adds capability in cli-serve to take and render snapshots as well as export those snapshots to images.
Makes it easier to debug the snapshot mode if something goes wrong.
closes #33
=> feat(cli-serve): add snapshotting capability

commands/serve/web/components/App.jsx, commands/serve/web/components/Cell.jsx, commands/serve/web/components/Chart.jsx, commands/serve/web/components/Collection.jsx, commands/serve/web/components/Stage.jsx, commands/serve/web/contexts/VizContext.js
- Adds an edit button which opens up the property panel for that object
- Adds an expand/collapse button which makes it easier to focus in individual objects
=> feat(cli-serve): enable expandable and editable cells

website/core/Footer.js
=> refactor(website): footer

commands/serve/lib/webpack.prod.js
Hackish regexbased attempt to improve sourcemaps and map files to original structure:
=> chore(cli-serve): attempt to improve sourcemaps

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/index.js, commands/serve/web/components/App.jsx, commands/serve/web/components/Cell.jsx, commands/serve/web/contexts/VizContext.js, commands/serve/web/eRender.js
- Apply theme in render route
- Make sure theme is applied in supernova cell
=> fix(cli-serve): apply theme in render route

apis/nucleus/src/__tests__/app-theme.spec.js, apis/nucleus/src/__tests__/nucleus.spec.js, apis/nucleus/src/app-theme.js, apis/nucleus/src/index.js
=> feat(nucleus): enable custom themes

.eslintrc.json, commands/create/templates/picasso/barchart/test/integration/interaction.int.js
=> test(create): attempt to fix timing issue after selection

apis/nucleus/src/components/selections/OneField.jsx, apis/nucleus/src/components/selections/SelectedFields.jsx, apis/nucleus/src/components/selections/__tests__/one-field.spec.jsx, apis/nucleus/src/components/selections/__tests__/selected-fields.spec.jsx, apis/nucleus/src/locale/translations/en-US.js, apis/nucleus/src/selections/app-selections.js, aw.config.js
Keep modal state in app selections when deselecting last value in listbox popover
Fixes #141
=> feat: keep modal state in app selections

apis/theme/package.json, apis/theme/spec/spec.conf.js, apis/theme/spec/spec.json, apis/theme/src/contraster.js, apis/theme/src/index.js, apis/theme/src/paletter-resolver.js, commands/sense/package.json, commands/sense/src/supernova-wrapper.js
Improvements to the theme API:
- add spec
- add color contrasting method
- fix merging of themes
=> feat(theme): add color contrast calculation

apis/nucleus/src/components/selections/OneField.jsx
Fix background color and position relative:
Before on the left, after on the right:
=> fix(nucleus): set bgColor and position

apis/nucleus/src/components/selections/MultiState.jsx, apis/nucleus/src/components/selections/OneField.jsx, apis/nucleus/src/components/selections/SelectedFields.jsx, apis/nucleus/src/locale/translations/en-US.js, packages/ui/components/index.js, packages/ui/icons/down-arrow.js
Handle multi state in app selections
Closes #160
=> feat: add multi state

apis/nucleus/src/components/SelectionToolbar.jsx, apis/nucleus/src/components/listbox/ListBoxPopover.jsx
On confirm accept selections
On cancel do not accept selections
=> fix: close list box popover on confirm and cancel

apis/nucleus/src/components/listbox/ListBoxRow.jsx, commands/serve/package.json, commands/serve/web/components/FieldsPopover.jsx, commands/serve/web/components/Search.jsx, yarn.lock
Add simple search functionality in fields popover
=> feat: add search to fields popover

commands/serve/web/components/App.jsx, commands/serve/web/connect.js, commands/serve/web/eRender.js
- Allow multiple listener for hot change
- Allow listening to change for multiple types
- Run callback when registered if type is already loaded
=> fix(cli-serve): improve handling of hot reload

.codesandbox/ci.json, .codesandbox/mekko/index.html, .codesandbox/mekko/package.json, .codesandbox/mekko/sandbox.config.json, .codesandbox/mekko/src/index.js, .codesandbox/mekko/src/init.js, .codesandbox/mekko/src/styles.css, package.json, rollup.config.js
=> chore: setup codesandbox ci

commands/serve/web/connect.js
Using `QCS/QSEOK` as backend follow login flow
=> feat: add tenant login

commands/serve/lib/webpack.build.js, commands/serve/lib/webpack.serve.js, commands/serve/package.json, commands/serve/web/components/PropertiesDialog.jsx, yarn.lock
Use the `monaco-editor` for the modify properties dialog.
=> feat: add monaco editor to properties dialog

.circleci/config.yml, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/Error.jsx, apis/nucleus/src/components/Header.jsx, apis/nucleus/src/components/Supernova.jsx, commands/create/templates/picasso/barchart/test/integration/interaction.int.js, test/integration/sn.int.js
Remove some wrapper elements and cleanup code
=> refactor: cleanup wrappers

apis/nucleus/src/components/Cell.jsx
Use `selections` instead of `sn.selections`so we don't crash
=> fix(nucleus): handle modal

commands/serve/web/eRender.js
Ensure only rendering once when hitting the `render` route.
TODO:
* Hot reloading needs to be fixed
=> refactor(cli-serve): render once

apis/nucleus/src/components/LongRunningQuery.jsx
=> fix(nucleus): use contained cancel button

apis/nucleus/src/components/LongRunningQuery.jsx, apis/nucleus/src/components/Progress.jsx
- Add a custom circular progress component
- Update long running query with a progress indicator
=> feat: custom circular progress

commands/create/templates/none/test/integration/hello.int.js, commands/create/templates/none/test/integration/setup.int.js, commands/create/templates/picasso/barchart/test/integration/interaction.int.js, commands/create/templates/picasso/common/test/integration/setup.int.js, test/integration/setup.int.js, test/integration/sn.int.js
Make it easier to run the integration tests while using `serve`
```
BASE_URL=http://localhost:8000 yarn test:integration
```
=> test: add `process.env.BASE_URL`

apis/nucleus/src/object/__tests__/create-object.spec.js, apis/nucleus/src/object/create-object.js
=> test: create object

.circleci/config.yml, commands/serve/lib/webpack.serve.js, package.json, test/component/object/incomplete-sn.comp.js, test/component/setup.comp.js, test/component/sn.js
=> test(component): enable

apis/nucleus/src/object/__tests__/hc-handler.spec.js, apis/nucleus/src/object/__tests__/populator.spec.js, apis/nucleus/src/object/hc-handler.js, apis/nucleus/src/object/populator.js, apis/nucleus/src/object/uid.js, apis/supernova/__tests__/unit/qae.spec.js, apis/supernova/src/qae.js
=> test: hc-handler

apis/nucleus/src/components/Cell.jsx
=> fix: show requirements for hypercubes

apis/nucleus/src/__tests__/viz.spec.js, apis/nucleus/src/object/get-object.js, apis/nucleus/src/viz.js
=> test: spice up viz

apis/nucleus/src/components/selections/OneField.jsx
Fix degrade caused by https://github.com/qlik-oss/nebula.js/commit/ed7e9df75f9f683b93e85ad65d58ab4f0dd257d1
=> fix: handle deselection of existing field

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/Header.jsx, apis/nucleus/src/components/Loading.jsx, apis/nucleus/src/components/__tests__/cell.spec.jsx, commands/serve/lib/webpack.serve.js, test/component/barchart/barchart.fix.js
=> test: spice up cell

apis/nucleus/src/components/Placeholder.jsx
Remove unused component `Placeholder`
=> chore: remove unused `Placeholder`

apis/nucleus/src/components/__tests__/glue.spec.jsx
=> test: spice up `glue`

apis/nucleus/src/components/__tests__/error.spec.jsx, apis/nucleus/src/components/__tests__/loading.spec.jsx
=> test: add `Error` and `Loading`

apis/nucleus/src/components/LongRunningQuery.jsx, apis/nucleus/src/components/__tests__/long-running-query.spec.jsx
=> test: spice up `LongRunningQuery`

apis/nucleus/src/components/__tests__/error.spec.jsx, apis/nucleus/src/components/__tests__/progress.spec.jsx
=> test: spice up `Progress`

apis/nucleus/src/components/__tests__/footer.spec.jsx
=> test: spice up `Footer`

apis/nucleus/src/components/__tests__/error.spec.jsx, apis/nucleus/src/components/__tests__/footer.spec.jsx, apis/nucleus/src/components/__tests__/header.spec.jsx, apis/nucleus/src/components/__tests__/loading.spec.jsx
=> test: spice up `Header`

apis/nucleus/src/components/Header.jsx, apis/nucleus/src/components/SelectionToolbar.jsx, apis/nucleus/src/components/SelectionToolbarItem.jsx, apis/nucleus/src/components/__tests__/selectiontoolbaritem.spec.jsx, apis/nucleus/src/components/listbox/ListBoxPopover.jsx
Add `SelectionToolbarItem` tests
Did some refactoring also
=> test: spice up `SelectionToolbarItem`

apis/nucleus/src/components/SelectionToolbarItem.jsx, apis/nucleus/src/components/__tests__/selectiontoolbar.spec.jsx
=> test: spice up `SelectionToolbar`

apis/nucleus/src/components/__tests__/supernova.spec.jsx
=> test: spice up `Supernova`

apis/nucleus/src/components/__tests__/nebulaapp.spec.jsx
=> test: spice up `NebulaApp`

apis/nucleus/src/components/NebulaApp.jsx
Give `NebulaApp` more responsibility and utilise React better
=> refactor: give `NebulaApp` more responsibility

apis/nucleus/src/__tests__/nucleus.spec.js, apis/nucleus/src/components/NebulaApp.jsx, apis/nucleus/src/components/__tests__/nebulaapp.spec.jsx, apis/nucleus/src/index.js
=> test: fix `NebulaApp`

apis/nucleus/src/__tests__/viz.spec.js, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/__tests__/cell.spec.jsx, apis/nucleus/src/components/__tests__/glue.spec.jsx, apis/nucleus/src/components/glue.jsx, apis/nucleus/src/index.js, apis/nucleus/src/object/__tests__/create-object.spec.js, apis/nucleus/src/object/__tests__/initiate.spec.js, apis/nucleus/src/object/create-object.js, apis/nucleus/src/object/get-object.js, apis/nucleus/src/object/initiate.js, apis/nucleus/src/object/populator.js, apis/nucleus/src/sn/__tests__/load.spec.js, apis/nucleus/src/sn/__tests__/type.spec.js, apis/nucleus/src/sn/__tests__/types.spec.js, apis/nucleus/src/sn/load.js, apis/nucleus/src/sn/type.js, apis/nucleus/src/sn/types.js, apis/nucleus/src/viz.js
=> refactor: improve naming of instance context

.eslintrc.json, apis/locale/index.js, apis/locale/package.json, apis/nucleus/index.js, apis/nucleus/package.json, apis/nucleus/src/__tests__/app-theme.spec.js, apis/nucleus/src/sn/__tests__/type.spec.js, apis/supernova/index.js, apis/supernova/package.json, apis/theme/index.js, apis/theme/package.json, aw.config.js, commands/serve/lib/webpack.build.js, commands/serve/package.json, rollup.config.js
=> chore: build dev distribution

apis/nucleus/src/sn/__tests__/type.spec.js, apis/nucleus/src/sn/type.js, apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/creator.js, apis/supernova/src/hooks.js, apis/supernova/src/index.js, rollup.config.js, test/component/hooks/hooked.fix.js, test/component/hooks/sn.comp.js
Initial hooks implementation to enable a more functional approach for supernova development.
#30
=> feat: hooks

apis/nucleus/src/components/Supernova.jsx, apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/creator.js, apis/supernova/src/hooks.js, apis/supernova/src/index.js, test/component/hooks/hooked.fix.js, test/component/hooks/sn.comp.js
=> fix: on render complete

apis/nucleus/src/components/__tests__/selectiontoolbar.spec.jsx, apis/nucleus/src/components/listbox/ListBoxPopover.jsx, apis/nucleus/src/components/selections/__tests__/selected-fields.spec.jsx, apis/nucleus/src/hooks/useRpc.js, apis/nucleus/src/stores/modelStore.js, commands/serve/web/eRender.js
Ensure we only render the listbox popover once when opening it
=> fix: render popover once

apis/nucleus/src/hooks/useRpc.js
Ensure returning correct result from `useRpc`
=> fix(use-rpc): return correct result

apis/nucleus/src/components/Supernova.jsx, apis/nucleus/src/components/__tests__/supernova.spec.jsx, apis/supernova/src/creator.js, commands/create/templates/picasso/barchart/test/integration/interaction.int.js
- fix initial mounting which was done twice due to snContext being changed from parent component
- fix resize of cell
- fix render throttle
=> fix: handle initial mount and render

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/Supernova.jsx, apis/nucleus/src/components/__tests__/cell.spec.jsx, apis/nucleus/src/components/__tests__/supernova.spec.jsx, apis/nucleus/src/hooks/useAppSelections.js, apis/snapshooter/src/renderer.js, apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/hooks.js, apis/supernova/src/index.js, commands/serve/web/eRender.js, test/component/hooks/hooked.fix.js, test/component/hooks/sn.comp.js, test/mashup/snaps/snapper.js
=> feat(hooks): add useAppLayout hook

apis/nucleus/src/components/__tests__/cell.spec.jsx, apis/nucleus/src/hooks/useRpc.js, apis/nucleus/src/stores/createKeyStore.js, apis/nucleus/src/stores/modelStore.js, commands/serve/web/components/Properties.jsx
=> fix(use-rpc): better rpc handling

apis/nucleus/package.json, apis/supernova/src/creator.js, commands/build/lib/build.js, commands/serve/lib/serve.js, commands/serve/package.json, commands/serve/web/hot.js, test/mashup/snaps/single.html, test/mashup/snaps/snapper.html
BREAKING CHANGE: supernova peer dependency
=> refactor: make supernova a peer dependency

apis/nucleus/src/hooks/useRpc.js
Add back `longrunning` api and cleanup `useRpc`
=> fix(use-rpc): add back longrunning api

commands/serve/web/components/App.jsx, commands/serve/web/components/Hub.jsx, commands/serve/web/storage.js
Remember last used websocket url in nebula hub, default to localhost:9076
=> feat: remember ws url in hub

examples/mashup/index.html, examples/sn-hello-react/.eslintrc.json, examples/sn-hello-react/package.json, examples/sn-hello-react/rollup.config.js, examples/sn-hello-react/src/components/Hello.jsx, examples/sn-hello-react/src/index.js, examples/sn-hello-react/yarn.lock
=> docs: update react example with hooks

apis/nucleus/src/components/selections/AppSelections.jsx, apis/nucleus/src/index.js
This avoids race conditions where the api could get overridden
=> fix(app-selections): pass api to portal

apis/nucleus/src/components/selections/AppSelections.jsx, apis/nucleus/src/index.js
Reverts qlik-oss/nebula.js#278
=> revert(app-selections): pass api to portal

apis/nucleus/src/hooks/useSessionModel.js
This ensures setting correct state when caching session models.
=> fix(use-session-model): ensure setting correct state

.codesandbox/mekko/package.json, .codesandbox/mekko/src/init.js
Fix codesandbox so it renders the mekko
=> fix(codesandbox): use nucleus and supernova next

apis/nucleus/src/object/initiate.js, commands/create/templates/picasso/barchart/src/data.js, commands/create/templates/picasso/common/src/pic-selections.js
- fix data path for picasso barchart template
- setOptions before mounting
=> fix: initiation of object and supernova

apis/nucleus/src/object/__tests__/get-object.spec.js, apis/nucleus/src/object/get-object.js, apis/nucleus/src/stores/createKeyStore.js, apis/nucleus/src/stores/modelStore.js
Ensure cleaning up cache on model close
=> fix: clean up cache on model close

apis/nucleus/src/object/get-object.js, apis/nucleus/src/stores/modelStore.js
=> fix(get-object): use separate store key

apis/nucleus/src/hooks/__tests__/use-rpc.spec.jsx, apis/nucleus/src/hooks/useRpc.js
=> test(use-rpc): spice up useRpc tests

apis/nucleus/src/hooks/__tests__/use-rect.spec.jsx
=> test(use-rect): spice up `useRect` tests

apis/nucleus/src/hooks/__tests__/use-app-selections-navigation.spec.jsx
Spice up `useAppSelectionsNavigation` tests
=> test: spice up `useAppSelectionsNavigation` tests

commands/serve/web/components/Hub.jsx, commands/serve/web/connect.js, commands/serve/web/eHub.html, packages/ui/icons/index.js
Improves the initial flow of selecting an engine and app:
- Adds instructions on how to connect with various Qlik products
- Remembers previous connections for faster flow
- Adds stepper which also functions as a navigator so that you can go back to selecting an engine
=> fix(cli-serve): improve initial connect flow

commands/sense/src/selections.js
The deleted code in this pr caused several BeginSelections to be called.
=> fix(cli-sense): avoid multiple beginSelections

commands/serve/lib/serve.js
=> fix(cli-serve): fix path separator on windows

apis/supernova/__tests__/unit/creator.spec.js, apis/supernova/spec/spec.json, apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/creator.js, apis/supernova/src/hooks.js, apis/supernova/src/index.js
- add `useOptions` hook
- add `useImperativeHandle` hook
- add test for `creator.js`
- add minor diffing in `run` so that functional components are called only when known values have changed
=> feat(supernova): add more hooks

apis/supernova/__tests__/unit/creator.spec.js, apis/supernova/src/creator.js
=> fix(nucleus): run only when layout changed

test/component/hooks/hooked.fix.js, test/component/hooks/sn.comp.js
=> test: component test of useOptions hook

apis/nucleus/src/components/SelectionToolbarItem.jsx, apis/nucleus/src/components/__tests__/selectiontoolbar.spec.jsx, apis/nucleus/src/components/__tests__/selectiontoolbaritem.spec.jsx, packages/ui/theme/definitions/dark.js
=> feat(nucleus): show active icons and hide hidden

apis/supernova/src/__tests__/json-patch.spec.js
=> test: add json-patch

apis/nucleus/src/components/selections/SelectedFields.jsx, apis/nucleus/src/hooks/__tests__/use-app-selections.spec.jsx, apis/nucleus/src/hooks/useAppSelections.js, apis/nucleus/src/stores/selectionsStore.js
Spice up `useAppSelections` tests
=> test: add `useAppSelections` tests

apis/nucleus/src/components/NebulaApp.jsx, commands/serve/lib/webpack.build.js, rollup.config.js
This will shorten the `productionPrefix` that is used in mui for generating class names
=> feat: use 4 character version hash

commands/serve/web/components/App.jsx, commands/serve/web/components/AutoComponents.jsx, commands/serve/web/components/FieldsPopover.jsx, commands/serve/web/components/Properties.jsx
- fix property panel update when switching between objects
- fix property panel visibility
=> fix(cli-serve): fix pp layout and update

apis/nucleus/src/hooks/__tests__/use-object-selections.spec.jsx, apis/nucleus/src/hooks/useObjectSelections.js
Spice up `useObjectSelections` tests
=> test: spice up `useObjectSelections` tests

aw.config.js, packages/ui/icons/__tests__/svg-icon.spec.jsx
=> test: spice up `<SvgIcon />` tests

apis/test-utils/src/__tests__/index.spec.js, aw.config.js
=> test: add `test-utils`

commands/create/templates/none/test/integration/hello.int.js, commands/create/templates/picasso/barchart/test/integration/interaction.int.js
Stabilize barchart integration test
=> test: stabilize barchart test

apis/nucleus/src/__tests__/nucleus.spec.js, apis/nucleus/src/__tests__/viz.spec.js, apis/nucleus/src/components/glue.jsx, apis/nucleus/src/index.js, apis/nucleus/src/object/__tests__/create-session-object.spec.js, apis/nucleus/src/object/__tests__/initiate.spec.js, apis/nucleus/src/object/create-session-object.js, apis/nucleus/src/object/initiate.js, apis/nucleus/src/stores/modelStore.js, apis/nucleus/src/viz.js, commands/serve/web/components/Chart.jsx, commands/serve/web/components/Stage.jsx
Ensure cleaning up listeners and stores on destroy
BREAKING CHANGE: change close to destroy
=> refactor: ensure cleanup on destroy

.codesandbox/mekko/src/init.js, apis/nucleus/spec/spec.json, apis/nucleus/src/__tests__/app-theme.spec.js, apis/nucleus/src/__tests__/nucleus.spec.js, apis/nucleus/src/index.js, apis/nucleus/src/object/__tests__/create-session-object.spec.js, apis/nucleus/src/object/__tests__/get-object.spec.js, apis/nucleus/src/object/create-session-object.js, apis/nucleus/src/object/get-object.js, apis/nucleus/src/viz.js, apis/snapshooter/src/__tests__/renderer.spec.js, apis/snapshooter/src/renderer.js, apis/supernova/spec/spec.json, apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/hooks.js, apis/theme/src/index.js, apis/theme/src/palette-resolver.js, commands/serve/web/components/Chart.jsx, commands/serve/web/components/Stage.jsx, commands/serve/web/eRender.js, examples/mashup/index.js, test/mashup/snaps/snapper.js
BREAKING CHANGE: deprecate nucleus get/create in favour of nucleus.render
=> refactor: refactor nucleus create/get

apis/nucleus/src/__tests__/nucleus.spec.js, apis/nucleus/src/index.js
=> fix: ensure merging configs without array duplication

apis/supernova/src/index.js
=> refactor: cleanup supernova exports

commands/serve/docker-compose.yml
Bump to latest `qlikcore/engine` docker.
=> chore: bump engine

.circleci/config.yml
Bump Circle CI docker dependencies.
=> chore: bump cci docker deps

commands/create/templates/none/test/integration/setup.int.js, commands/create/templates/picasso/common/test/integration/setup.int.js, test/integration/setup.int.js, test/mashup/setup.int.js
Normalize all test integration `setup.int.js` to always hook up page events.
=> test: always setup page events

apis/nucleus/spec/spec.json, apis/nucleus/src/index.js, docs/nucleus-reference.md
=> docs(nucleus): update jsdoc

apis/supernova/spec/spec.conf.js, apis/supernova/spec/spec.json, apis/supernova/src/generator.js, apis/supernova/src/qae.js, docs/supernova-api.md, website/i18n/en.json
=> docs(supernova): update jsdoc

apis/locale/locales/en-US.json
Prepare locale files for easier translation per locale
=> chore: prepare locale format

apis/nucleus/src/components/__tests__/cell.spec.jsx, apis/nucleus/src/components/__tests__/supernova.spec.jsx, apis/nucleus/src/components/selections/More.jsx, apis/nucleus/src/components/selections/MultiState.jsx, apis/nucleus/src/components/selections/OneField.jsx, apis/nucleus/src/components/selections/SelectedFields.jsx, apis/nucleus/src/components/selections/__tests__/more.spec.jsx, apis/nucleus/src/components/selections/__tests__/multi-state.spec.jsx, apis/nucleus/src/components/selections/__tests__/selected-fields.spec.jsx, apis/nucleus/src/hooks/__tests__/use-rect.spec.jsx, commands/serve/web/components/App.jsx
Responsive app selections toolbar.
Closes #326
=> feat: responsive app selections

apis/nucleus/src/components/NebulaApp.jsx, apis/nucleus/src/components/__tests__/nebulaapp.spec.jsx
Spice up `<NebulaApp />` tests.
=> test: spice up `<NebulaApp />` tests

apis/supernova/__tests__/unit/creator.spec.js, apis/supernova/src/creator.js
Fix issue where only changed properties were updated
=> fix(supernova): update all options

apis/nucleus/src/components/SelectionToolbar.jsx
Align the listbox popover more menu.
=> fix: align listbox popover more menu

apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/hooks.js
=> fix(supernova): handle multiple useRect

commands/serve/web/components/App.jsx, commands/serve/web/components/Properties.jsx
=> fix(cli-serve): used shared storage

commands/serve/web/components/App.jsx
Removes React warning after dependency updates
=> fix(cli-serve): remove react warning

apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/hooks.js
=> fix: store action dispatcher when called before component initiation

apis/nucleus/src/components/ActionsToolbar.jsx
Ensure not getting into a never ending loop
=> fix: custom actions

apis/nucleus/src/hooks/__tests__/use-rect.spec.jsx, apis/nucleus/src/hooks/useRect.js
=> fix: set initial rect when ResizeObserver is undefined

commands/build/lib/build.js, commands/sense/lib/build.js, commands/sense/src/ext.js
=> chore(cli): build core esm module

apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/hooks.js
=> fix: hide action when hidden is true

apis/locale/locales/README.md, apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
This is a preparatory step to monitor the English strings to ensure translation updates in other languages.
=> chore: prepare for automated translation updates

commands/serve/web/components/Hub.jsx
Use `qDocName` if it's treated as desktop.
=> fix: desktop app name

apis/locale/locales/en-US.json
Add translation for `Menu.More`
=> docs: add `Menu.More` translation

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
feat(translations): UI bus - 2020-05-20
- Update translations related to: 26c4466 - docs: add `Menu.More` translation (#428)
=> feat(translations): UI bus - 2020-05-20

apis/nucleus/src/hooks/usePropertiesById.js, apis/nucleus/src/object/create-session-object.js, apis/nucleus/src/viz.js, commands/serve/web/components/Properties.jsx, commands/serve/web/components/Stage.jsx, commands/serve/web/components/property-panel/Data.jsx, commands/serve/web/components/property-panel/HyperCube.jsx
=> chore: cleanup `viz`

apis/locale/src/translator.js, apis/nucleus/src/__tests__/viz.spec.js, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/__tests__/cell.spec.jsx, apis/nucleus/src/index.js, apis/nucleus/src/sn/__tests__/load.spec.js, apis/nucleus/src/sn/load.js, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/supernova/src/__tests__/hooks.spec.js, apis/supernova/src/generator.js, apis/supernova/src/hooks.js
Rename supernova to visualization and add some missing API docs.
BREAKING CHANGE: renamed setTemporaryProperties to applyProperties
=> refactor: update API and docs

commands/create/templates/sn/none/_package.json, commands/create/templates/sn/picasso/common/_package.json
=> chore: add `sense` to templates

commands/build/README.md, commands/build/command.js, commands/cli/README.md, commands/create/README.md, commands/create/command.js, commands/sense/README.md, commands/sense/command.js, commands/serve/README.md
=> docs: update command docs

apis/test-utils/package.json
=> chore: private test-utils

apis/test-utils/package.json, commands/cli/package.json, commands/create/templates/sn/none/_package.json, commands/create/templates/sn/picasso/common/_package.json
=> chore: update peerDeps

README.md
=> docs: fix link to api refs in qlik.dev

apis/nucleus/src/components/selections/SelectedFields.jsx, apis/nucleus/src/components/selections/__tests__/selected-fields.spec.jsx, apis/nucleus/src/hooks/__tests__/use-app-selections.spec.jsx, apis/nucleus/src/hooks/__tests__/use-object-selections.spec.jsx, apis/nucleus/src/hooks/__tests__/use-rpc.spec.jsx, apis/nucleus/src/hooks/useAppSelections.js, apis/nucleus/src/hooks/useObjectSelections.js, apis/nucleus/src/hooks/usePropertiesById.js, apis/nucleus/src/hooks/useRpc.js, apis/nucleus/src/hooks/useSessionModel.js, apis/nucleus/src/object/create-session-object.js, apis/nucleus/src/object/get-object.js, apis/nucleus/src/stores/__tests__/create-key-store.spec.jsx, apis/nucleus/src/stores/create-key-store.js, apis/nucleus/src/stores/model-store.js, apis/nucleus/src/stores/selections-store.js
Ensure we can destroy session objects gracefully.
=> fix: destroy session object

apis/locale/locales/README.md
This clarifies how to proceed when adding or modifying strings.
=> chore(locales): Update README.md for string resources

renovate.json
=> chore: monthly renovation

.circleci/config.yml, apis/locale/locales/de.json, apis/locale/locales/en-US.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/Error.jsx, apis/nucleus/src/components/__tests__/cell.spec.jsx, apis/nucleus/src/components/__tests__/error.spec.jsx, apis/supernova/__tests__/unit/qae.spec.js, apis/supernova/src/qae.js, commands/serve/web/eRender.js
Add better visual feedback for incomplete visualizations.
For visualizations with multiple hypercubes we use one list with combined dimensions and measures:
Closes #422
=> feat: better incomplete view

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/Error.jsx, apis/nucleus/src/components/__tests__/cell.spec.jsx
Ensure checking all cubes for errors
Use `<Icon />`
=> fix: incomplete

.circleci/config.yml
=> chore: improve caching

commands/serve/lib/engine.js, scripts/start-mashup.js, test/mashup/visualize/life.int.js, test/mashup/visualize/phases.js
=> test: add hypercube error test

commands/serve/web/components/App.jsx, commands/serve/web/components/Stage.jsx
=> fix: ensure hot reload works

test/mashup/visualize/life.int.js, test/mashup/visualize/phases.js
=> test: verify spinner on slow loading

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/__tests__/cell.spec.jsx, test/mashup/visualize/life.int.js
Ensure loading new type if the layout has changed
=> fix: ensure loading new type

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
feat(translations): UI bus - 2020-07-03
- Update translations related to: e9d11e9 - feat: better incomplete view (#453)
=> fix(translations): UI bus - 2020-07-03

commands/serve/web/components/property-panel/Fields.jsx
Fix warning for unique key prop in `Fields`
=> fix: warning unique key prop in `Fields`

.storybook/config.js, apis/nucleus/src/components/selections/__stories__/app-selections.jsx, apis/nucleus/src/components/selections/__stories__/multi-field.jsx, apis/nucleus/src/components/selections/__stories__/one-field.jsx, apis/nucleus/src/hooks/__tests__/use-app-selections.spec.jsx, apis/nucleus/src/hooks/__tests__/use-object-selections.spec.jsx, apis/nucleus/src/hooks/useAppSelections.js, apis/nucleus/src/hooks/useObjectSelections.js
=> fix: set state value when caching stored value

apis/nucleus/src/components/ActionsToolbar.jsx
This ensures we update the more enabled button when for example locking/unlocking in the list box popover
=> fix: update more enabled status

commands/create/templates/mashup/src/configure.js
=> fix(cli-create): import stardust index

commands/sense/lib/build-legacy.js
=> fix(cli-sense): fix path injection on windows

commands/serve/web/components/Hub.jsx, commands/serve/web/connect.js
Slightly improves engine connection error messages and instructions to make it easier for users to understand what went wrong and how to fix it.
=> fix(cli-serve): improve connection error messages

apis/theme/src/__tests__/theme-scale-generator.spec.js, apis/theme/src/color-scale.js, apis/theme/src/palette-resolver.js, apis/theme/src/style-resolver.js, apis/theme/src/theme-scale-generator.js
implements the // TODO - generate class-pyramid
matching what is done in the sense client
=> fix(stardust): support class-pyramid in theme

examples/sn-hello-react/package.json, examples/sn-hello-react/yarn.lock
=> chore: update deps

.circleci/config.yml, apis/stardust/api-spec/spec.conf.js, apis/stardust/api-spec/spec.json, apis/stardust/package.json, apis/stardust/scriptappy.json, apis/theme/src/color-scale.js, apis/theme/src/theme-scale-generator.js
Add connection to API governance.
TODO: add spec build as part of ci as a later PR.
=> chore: add api gov job

examples/dev-mashup/.gitignore, examples/dev-mashup/README.md, examples/dev-mashup/connect.js, examples/dev-mashup/index.html, examples/dev-mashup/index.js, examples/dev-mashup/package.json
To simplify nebula development we add an mashup example targeting development of nebula itself.
=> chore: add dev mashup example

apis/nucleus/src/__tests__/viz.spec.js, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/__tests__/cell.spec.jsx, apis/nucleus/src/object-conversion/__tests__/index.spec.js, apis/nucleus/src/object-conversion/index.js, apis/nucleus/src/viz.js, apis/supernova/__tests__/unit/qae.spec.js, apis/supernova/src/qae.js
This PR is the first step to support object conversion.
=> feat: add basic support for object conversion

apis/conversion/package.json, apis/conversion/src/__tests__/array-util.spec.js, apis/conversion/src/__tests__/index.spec.js, apis/conversion/src/array-util.js, apis/conversion/src/helpers/__tests__/index.spec.js, apis/conversion/src/helpers/index.js, apis/conversion/src/hypercube.js, apis/conversion/src/index.js
This PR is to add importProperties for hypercube conversion.
TODO:
1. add more unit tests
2. prepare for document
=> feat: add importProperties for hypercube conversion

apis/conversion/src/export-format.js, apis/conversion/src/helpers/__tests__/index.spec.js, apis/conversion/src/helpers/index.js, apis/conversion/src/hypercube/export-properties.js, apis/conversion/src/hypercube/import-properties.js, apis/conversion/src/hypercube/index.js, apis/conversion/src/index.js, apis/nucleus/src/__tests__/viz.spec.js, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/object/create-session-object.js, apis/nucleus/src/object/get-object.js, apis/nucleus/src/object/populator.js, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.conf.js, apis/stardust/api-spec/spec.json, apis/stardust/src/index.js, apis/supernova/src/qae.js
Updates jsdoc spec for object conversion.
Moves from ignored to experimental.
=> chore: update spec for object conversion

docs/sn-create.md, docs/sn-selections.md
=> chore: tweak docs

apis/conversion/src/export-format.js, apis/stardust/api-spec/spec.json, apis/stardust/package.json, package.json
=> chore: hide function in spec

apis/nucleus/src/viz.js, apis/supernova/src/creator.js
=> fix: remove setProperties interceptor on object conversion

apis/conversion/src/helpers/__tests__/index.spec.js, apis/conversion/src/helpers/index.js, apis/conversion/src/hypercube/__tests__/import-properties.spec.js, apis/conversion/src/hypercube/import-properties.js
This PR is to fix #564 by adding necessary properties for dimensions/measures on conversion.
=> fix: update dimensions and measures on object conversion

examples/sn-hello-react/package.json, examples/sn-hello-react/rollup.config.js, examples/sn-hello-react/yarn.lock
=> chore: update react example deps

examples/sn-hello-react/package.json, examples/sn-hello-react/yarn.lock
=> chore: update react example

docs/sn-create.md
=> docs: fix missing column in selections call

examples/dev-mashup/README.md, examples/dev-mashup/index.html, examples/dev-mashup/index.js
=> chore: update local dev environment

apis/nucleus/src/__tests__/nucleus.spec.js, apis/nucleus/src/device-type.js, apis/nucleus/src/index.js, apis/stardust/src/index.js, apis/supernova/__tests__/unit/creator.spec.js, apis/supernova/src/creator.js, apis/supernova/src/hooks.js, apis/supernova/src/index.js, commands/sense/src/legacy/sn-ext.js, test/component/hooks/hooked.fix.js, test/component/hooks/sn.comp.js
implement #573 (Set/consume preferred change device type)
=> feat: add device type

apis/nucleus/src/sn/__tests__/load.spec.js, apis/nucleus/src/sn/load.js
Adds error to type load function.
=> chore: add error for incorrect load function

apis/conversion/src/export-format.js, apis/conversion/src/index.js, apis/locale/src/translator.js, apis/nucleus/src/hooks/useAppSelections.js, apis/nucleus/src/hooks/useObjectSelections.js, apis/nucleus/src/index.js, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/supernova/src/hooks.js, apis/theme/src/index.js, docs/api-reference.md
Fixes spelling and grammar
TODO
=> chore: import editorial review

commands/serve/web/components/App.jsx
missed when the change from key to id was done #347
=> fix(serve): fix themes to use id, not key

commands/serve/lib/webpack.serve.js, commands/serve/web/connect.js
=> chore: flags in config

commands/build/lib/build.js, commands/build/package.json, yarn.lock
=> feat(cli-build): include source maps of dependencies

commands/sense/lib/build-legacy.js, commands/sense/lib/build.js, commands/sense/src/legacy/sn-ext.js
=> feat: update build and build legacy for nebula sense

commands/serve/lib/init-config.js, commands/serve/lib/serve.js
=> fix(cli-serve): apply config when using javascript API and handle missing serve

commands/sense/command.js, commands/sense/lib/api-entry.js, commands/sense/lib/init-config.js, commands/sense/lib/sense.js, commands/sense/package.json
=> fix(cli-sense): apply default when using javascript api

.circleci/config.yml
Updating node for circle build to fix dependency compatability
=> chore: update to node 16

commands/create/README.md
=> docs(create-cli): add docs to create mashup cli

commands/sense/src/legacy/selections.js
=> fix: use same event in extension wrapper

.circleci/config.yml, commands/create/templates/mashup/_package.json, commands/create/templates/mashup/src/index.html
Updates faulty parcel dependency to 2.0.
Adds test for mashup creation and build
=> fix: update mashup dependencies

apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/index.js, apis/stardust/api-spec/spec.json
Request to be able to sort the internal listbox.
- Added options.properties to allow manipulation of the inline libox properties.
=> feat: add properties option to Field function

commands/build/README.md, commands/build/lib/init-config.js
a hidden --core command info for nebula build should be added
=> feat(nebula-build-core): add docs and help info

commands/cli/README.md
add docs to run nebula cli commands with Node.js
=> docs(nebula-cli): run nebula cli commands with Node.js

commands/create/README.md
example docs for nebula create
=> docs(nebula-create): add example docs for nebula create

commands/build/README.md
=> docs(nebula-build): add docs for nebula build

commands/build/README.md, commands/build/lib/build.js, commands/build/lib/init-config.js, commands/build/package.json, yarn.lock
Adding the support for typescript in nebula build
=> feat(build): add typescript support in build

renovate.json
=> chore: enable renovate to update node version

.codesandbox/mekko/src/init.js, commands/create/templates/mashup/src/connect.js, commands/serve/web/connect.js, examples/chart-conversion/connect.js, examples/dev-mashup/connect.js, examples/mashup/connect.js
use engine schema version 12.936.0 in nebula serve, templates and examples.
=> refactor: update engine schema version

apis/stardust/api-spec/spec.json, apis/theme/src/index.js, docs/api-reference.md
=> docs: remove extra right bracket

apis/stardust/api-spec/spec.conf.js, apis/stardust/api-spec/spec.json, apis/stardust/package.json, yarn.lock
Use `@scriptappy/from-jsdoc` to generate api specification for stardust.
Modified api specification config (`api-spec/spec.conf.js`) to new format.
=> chore(stardust): generate api spec using @scriptappy/from-json

.circleci/config.yml
=> chore: update api compliance

apis/nucleus/src/object/create-session-object.js, apis/nucleus/src/sn/type.js
version is optional and it should be reflected in the spec
=> fix: mark version as optional

apis/nucleus/src/index.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
=> fix(jsdoc): mark mount and unmount  as instance functions

commands/build/lib/resolveNative.js
This fixes an invalid parameter in resolveNative
=> fix: change carbon to reactNative

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
chore(translations): UI bus - 2022-03-08
- Update translations related to: 7b55e65 - refactor(Listbox): Search and style improvements (#775)
=> chore(translations): UI bus - 2022-03-08

apis/nucleus/src/components/listbox/ListBoxCheckbox.jsx, apis/nucleus/src/components/listbox/ListBoxRowColumn.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-checkbox.spec.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-row-column.spec.jsx
Added gray fill to checkboxes when in state excluded or alternative
=> feat(Listbox): add fill to checkboxes with state excluded or alternative

.github/workflows/semantic.yml
=> chore: add semantic pr action

apis/nucleus/src/components/listbox/ListBoxInline.jsx
Fix to the following error, when unmounting.
=> fix: remove event listeners when unmounting

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxCheckbox.jsx, apis/nucleus/src/components/listbox/ListBoxRowColumn.jsx
Make the rows even denser when dense in enabled. Remove row divider when histogram and dense is enabled.
=> fix(ac): looks

apis/nucleus/src/components/listbox/ListBoxRowColumn.jsx
Color did not change on select when `row:` was a function in `makeStyles()`
This change should fix it.
=> fix(Listbox): apply color when selecting

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/index.js
Pass current scroll state to hosting app. Set initial scroll position.
=> feat(Listbox): scroll state

.github/CONTRIBUTING.md, .storybook/webpack.config.js, apis/locale/locales/README.md, scripts/start-mashup.js
- format code using yarn format
- in contributing doc:
- add desc for some packages
- complete development workflow
=> docs(contributing): add packages and development worlflow

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/index.js
Write the length/count of the list as a parameter to a passed function.
=> feat: data count to hosting app

apis/nucleus/src/components/listbox/useSelectionsInteractions.js
=> fix: layout timing with qIsOneAndOnlyOne

apis/nucleus/src/components/listbox/listbox-selection-toolbar.js, apis/nucleus/src/components/selections/OneField.jsx, apis/nucleus/src/hooks/useObjectSelections.js
=> fix: fix OneAndOnlyOne in app and object selection toolbar

apis/nucleus/package.json, apis/nucleus/src/components/ClassNameSetup.js, apis/nucleus/src/components/NebulaApp.jsx, apis/stardust/core/package.json, apis/stardust/package.json, commands/serve/package.json, packages/ui/package.json, packages/ui/theme/index.js, yarn.lock
=> chore: get rid of legacy package

apis/nucleus/src/components/selections/MultiState.jsx
Fix https://github.com/qlik-oss/nebula.js/issues/854
=> fix: multistate style

apis/nucleus/src/components/listbox/ListBoxRadioButton.jsx, apis/nucleus/src/components/listbox/ListBoxRowColumn.jsx
=> fix: add italic to checkbox text when excluded

apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/ListBoxRowColumn.jsx
=> fix: horizontal listbox

apis/nucleus/src/components/Cell.jsx
=> fix: the selections is missing in dependency arrays (#865)

apis/nucleus/src/components/listbox/ListBox.jsx
Made this fix very explicit so that it is not hard to miss (+1 on line 222 would have looked slicker)
***OR***
=> fix: issue with empty search results in listbox

apis/stardust/types/index.d.ts, commands/cli/package.json, commands/create/templates/sn/picasso/common/_package.json
=> chore: update internal references

apis/test-utils/package.json, commands/cli/package.json, commands/create/templates/sn/none/_package.json, commands/create/templates/sn/picasso/common/_package.json
=> chore: fix cli by changing to use alpha version

apis/nucleus/src/index.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
=> docs: stateName should be a string

apis/enigma-mocker/src/index.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
Fix missed jsdoc description
***OR***
=> fix: adjust enigma mocker comment

commands/create/templates/mashup/_package.json
Update barchart version in create mashup
***OR***
=> chore: update bc version in mashup template

.github/CONTRIBUTING.md, commands/cli/README.md
To better understand packages' relations
***OR***
=> docs: visualize packages

.circleci/config.yml
=> feat: jest coverage report

apis/nucleus/src/components/listbox/ListBoxInline.jsx
Fixes an error thrown when activating search through the DQ Filter pane.
***OR***
=> fix: prevent error by ensuring removeListener exists

.eslintrc.json, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/Supernova.jsx, apis/theme/src/index.js
Made some alterations to the bg color logic and fixed fetching the base URL for images when using media library.
***OR***
=> chore: cleanup and fix bg image url

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/Supernova.jsx, apis/nucleus/src/utils/__tests__/background-props.spec.js, apis/nucleus/src/utils/background-props.js
Adjusts so that the bg covers the entire cell
***OR***
=> chore: adjust bg and add tests

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
chore(translations): UI bus - 2022-10-21
- Update translations related to: 03641e1 - fix(a11y): Casey's access fixes (#966)
=> chore(translations): UI bus - 2022-10-21

commands/serve/web/components/Hub/SelectEngine/FormManager.jsx, commands/serve/web/components/Hub/SelectEngine/__tests__/FormManager.inspect.jsx, commands/serve/web/hooks/__tests__/useAppList.inspect.js, commands/serve/web/hooks/__tests__/useCachedConnection.inspect.js, commands/serve/web/hooks/__tests__/useConnection.inspect.js, commands/serve/web/hooks/__tests__/useInfo.inspect.js, commands/serve/web/hooks/__tests__/useLibraryList.inspect.js, commands/serve/web/hooks/__tests__/useOpenApp.inspect.js, commands/serve/web/utils/__tests__/formUrils.inspect.js, commands/serve/web/utils/formUtils.js, commands/serve/web/utils/index.js, commands/serve/web/utils/testRenderer.jsx
- `<FormManager />` from components directory
-  `formUtils.js`
- `commands/serve/web/hooks` directory done
=> test: hooks directory in `commands/serve/web` is covered

apis/locale/locales/de.json, apis/locale/locales/en-US.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json, apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/__tests__/list-box.test.jsx, apis/nucleus/src/components/listbox/components/ListBoxDisclaimer.jsx
Show a disclaimer in Listbox when search has no results
https://github.com/qlik-oss/nebula.js/issues/1025
Unit test will be updated/added in an another PR
https://user-images.githubusercontent.com/13185716/208091034-3eb0a85a-cd4b-463b-ae33-d1b5ee81636e.mov
=> feat: add disclaimer listbox search

apis/nucleus/src/components/listbox/components/ListBoxRowColumn.jsx, apis/nucleus/src/components/listbox/components/__tests__/list-box-row-column.test.jsx
=> fix: prevent rendering empty values

package.json
No parser could be inferred for some files
=> fix: error when doing format

package.json, yarn.lock
=> chore: lerna v6.4.1

.circleci/config.yml
=> chore: try speed up build

apis/conversion/src/index.js, apis/enigma-mocker/src/index.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
=> chore!: fix typings for mocker

commands/serve/package.json
=> fix: move qlik-sdk dependency

commands/serve/web/components/Visualize/Chart.jsx, commands/serve/web/eRender.html
=> fix: set container bg to white in serve

apis/nucleus/src/__tests__/index.test.js, apis/nucleus/src/__tests__/nucleus.test.js, apis/nucleus/src/components/NebulaApp.jsx, apis/nucleus/src/components/__tests__/glue.test.jsx, apis/nucleus/src/components/glue.jsx, apis/nucleus/src/components/listbox/ListBoxPopover.jsx, apis/nucleus/src/components/listbox/ListBoxPopoverWrapper.jsx, apis/nucleus/src/components/listbox/ListBoxPortal.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-portal.test.jsx, apis/nucleus/src/components/selections/AppSelections.jsx, apis/nucleus/src/components/selections/__tests__/app-selections.test.jsx, apis/nucleus/src/index.js
Adds an experimental listbox popover API under DO_NOT_USE (for now). Also fixes some issues with React portals and missing keys,
=> feat: listbox popover api

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
chore(translations): UI bus - 2023-01-27
- Update translations related to: ed97b08 - feat(Listbox): overflow disclaimer (#1059)
=> chore(translations): UI bus - 2023-01-27

apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/components/ListBoxSearch.jsx, apis/nucleus/src/components/listbox/components/__tests__/list-box-search.test.jsx
https://user-images.githubusercontent.com/13185716/216378142-34623336-3fdf-40c1-91df-16c527601988.mov
=> feat: wildcard search

apis/nucleus/src/components/listbox/ListBoxPortal.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-portal.test.jsx, apis/nucleus/src/hooks/useObjectSelections.js, apis/nucleus/src/index.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
Listen to selection events in Listbox from hosting app
=> feat(Listbox): add selection events

apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/components/ListBoxSearch.jsx, apis/nucleus/src/components/listbox/components/__tests__/list-box-search.test.jsx
Add `searchEnabled` property so that the user is able to disable the search setting in listbox.
https://user-images.githubusercontent.com/13185716/219059306-343e30d6-6a7a-468f-a8ce-6aba13cb9e2c.mov
=> feat: add property for disabling listbox search

commands/build/lib/build.js, commands/sense/lib/build-legacy.js, commands/sense/lib/build.js
=> chore: set default value for babelHelpers

commands/serve/web/components/Visualize/Visualize.jsx
=> fix: update constraints in serve command

.circleci/config.yml
Run API Compliance test with a patch version bump
to avoid "Changes in an already existing API version" errors
=> chore: improve version used in api-governance build

apis/nucleus/src/index.js, apis/nucleus/src/sn/types.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
Documents the global load fallback function on config. 
Additionally moves some jsdoc around and adds examples to improve the docs.
=> docs: add load to config

apis/nucleus/src/components/selections/SelectedFields.jsx, apis/nucleus/src/components/selections/__tests__/selected-fields.test.jsx
Hides hidden fields in the app selections
=> fix: correctly hide hidden fields in app selections

apis/nucleus/src/components/listbox/ListBoxInline.jsx
=> fix(Listbox): truncate title, don't wrap title

.gitignore, package.json, yarn.lock
=> fix(storybook): missing deps and ignore storybook-static

apis/nucleus/src/components/NebulaApp.jsx, apis/nucleus/src/components/__tests__/nebulaapp.test.jsx
part of fix for performance problem in qlik-oss/sn-list-objects#105
=> fix: avoid re-render on unchanged-context

apis/nucleus/src/components/listbox/ListBoxInline.jsx
fix part of qlik-oss/sn-list-objects#65
=> feat: add tooltip for listbox title

apis/nucleus/src/components/listbox/components/ListBoxRowColumn/ListBoxRowColumn.jsx, apis/nucleus/src/components/listbox/components/ListBoxRowColumn/__tests__/list-box-row-column.test.jsx, apis/nucleus/src/components/listbox/hooks/selections/__tests__/use-selections-interactions.test.jsx, apis/nucleus/src/components/listbox/hooks/selections/useSelectionsInteractions.js
(maybe also abort selection if multiple buttons are pressed?)
fix qlik-oss/sn-list-objects#68
=> fix: only select with main mouse button

apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/__tests__/list-box-inline.test.jsx
Use correct functions when removing `activated` and `deactivated` listeners to prevent memory leaks.
=> fix(ListBoxInline): remove correct event listeners

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
chore(translations): UI bus - 2023-03-14
- Update translations related to: f679e96 - fix: show drilldown icon for drilldown dimension (#1129)
=> chore(translations): UI bus - 2023-03-14

apis/nucleus/src/components/listbox/ListBox.jsx, apis/nucleus/src/components/listbox/assets/get-list-sizes/__tests__/get-list-sizes.test.jsx, apis/nucleus/src/components/listbox/assets/get-list-sizes/column-mode.js, apis/nucleus/src/components/listbox/assets/get-list-sizes/constants.js, apis/nucleus/src/components/listbox/assets/get-list-sizes/get-list-sizes.js, apis/nucleus/src/components/listbox/assets/get-list-sizes/row-mode.js
- fixes(https://github.com/qlik-oss/sn-list-objects/issues/156)
=> refactor: account for checkboxes in item min width

apis/nucleus/src/components/ActionsToolbar.jsx
Updates position of selection toolbar to better align with UI changes in Qlik Sense.
Before:
After:
=> refactor: adjust position of actions toolbar

apis/nucleus/src/components/listbox/ListBox.jsx
`renderedCallback` is undefined in popover mode
=> fix(Listbox): null check rendered callback

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
chore(translations): UI bus - 2023-03-21
- Update translations related to: e8a17b5 - fix: add tooltip lock button (#1158)
=> chore(translations): UI bus - 2023-03-21

apis/nucleus/src/components/listbox/ListBoxInline.jsx
To fix https://github.com/qlik-oss/sn-list-objects/issues/216.
=> fix(ListBox): show detached toolbar when layout.toolbar is false

apis/nucleus/src/components/listbox/hooks/selections/useSelectionsInteractions.js, apis/nucleus/src/components/listbox/interactions/__tests__/list-box-keyboard-navigation.test.js, apis/nucleus/src/components/listbox/interactions/listbox-keyboard-navigation.js
fix qlik-oss/sn-list-objects#190
=> fix: do ctrl-select on ctrl-space

apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/components/ListBoxError.jsx
To fix https://github.com/qlik-oss/sn-list-objects/issues/79
=> fix(listbox): invalid dimension error message

apis/nucleus/src/hooks/useObjectSelections.js
=> fix: confirm selection when object is removed

apis/nucleus/src/components/listbox/components/ListBoxDisclaimer.jsx, apis/nucleus/src/components/listbox/components/ListBoxError.jsx
Refactor to avoid performance issue and other potential issue of creating a component inside another component.
=> refactor: avoid defining a component inside another component

apis/nucleus/src/hooks/__tests__/use-object-selections.test.jsx
https://github.com/qlik-oss/nebula.js/pull/992#discussion_r1010237675
=> test: fix and enable useObjectSelection tests

apis/nucleus/src/components/listbox/components/ListBoxRowColumn/components/ItemGrid.jsx
=> fix: shouldForwardProp to fix React warning

apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/interactions/__tests__/listbox-show-toolbar-detached.test.js, apis/nucleus/src/components/listbox/interactions/listbox-show-toolbar-detached.js
fix qlik-oss/sn-list-objects#257
=> fix: refactor to work with Grid flex styling

apis/nucleus/src/components/listbox/components/ListBoxRowColumn/ListBoxRowColumn.jsx, apis/nucleus/src/components/listbox/components/ListBoxRowColumn/components/ItemGrid.jsx, apis/nucleus/src/components/listbox/components/ListBoxRowColumn/components/ListBoxRoot.jsx
To fix https://github.com/qlik-oss/sn-list-objects/issues/193 and positioning of frequency count and row value when it is a number.
=> fix: fix rtl for histogram and checkbox and frequency count

apis/nucleus/src/components/ActionsToolbar.jsx, apis/nucleus/src/components/actions-toolbar-keydown.js, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/interactions/listbox-get-action-props.js
=> fix: escape in toolbar

apis/nucleus/src/components/listbox/default-properties.js, apis/nucleus/src/components/listbox/hooks/__tests__/useOnTheFlyModel.test.jsx, apis/nucleus/src/components/listbox/hooks/useOnTheFlyModel.jsx, apis/nucleus/src/object/__tests__/create-object.test.js, apis/nucleus/src/object/__tests__/create-session-object.test.js, apis/nucleus/src/object/__tests__/filterpane-handler.test.js, apis/nucleus/src/object/__tests__/populator.test.js, apis/nucleus/src/object/create-object.js, apis/nucleus/src/object/create-session-object.js, apis/nucleus/src/object/filterpane-handler.js, apis/nucleus/src/object/populator.js
=> feat: add filterpane handler for creating filterpane objects

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
chore(translations): UI bus - 2023-03-31
- Update translations related to: 5d1399f - refactor: add basic screen reader support and keyboard nav improvements (#1178)
=> chore(translations): UI bus - 2023-03-31

apis/nucleus/src/components/listbox/ListBoxInline.jsx
fixes: https://github.com/qlik-oss/sn-list-objects/issues/280
Before:
After:
=> fix(listbox): add box-shadow to scrollbar when focus

README.md, commands/create/README.md, commands/create/templates/sn/none/src/index.js, commands/create/templates/sn/picasso/common/src/index.js, docs/README.md, examples/sn-hello-react/src/index.js
=> docs: fix links to qlik.dev

commands/serve/web/render-fixture.js
used in https://github.com/qlik-oss/sn-table/pull/997 to test a11y
`/render?fixture=sn-locale.fix.js&language=sv-SE&keyboardNavigation=true`
=> feat: support keyboardNavigation in fxiture rendering

apis/nucleus/src/components/listbox/components/ListBoxSearch.jsx
=> fix: move focus on (one case of) close search

apis/nucleus/src/components/listbox/ListBoxInline.jsx
=> fix: mark invalid listboxes as rendered

apis/nucleus/src/components/listbox/components/ListBoxRowColumn/components/Frequency.jsx
Add a popup to frequency count
Fix for https://jira.qlikdev.com/browse/QB-19439
https://github.com/qlik-oss/nebula.js/assets/13185716/9a0569cd-ec94-4928-956a-c34865f3fa37
=> fix: listbox frequency count popup

.circleci/config.yml, test/bin/README.md
=> chore: switch to codeclimate

.circleci/config.yml
=> chore: add listbox to api gov

.circleci/config.yml
Splits the CI into jobs to make it faster (hopefully) and easier to view
=> chore: split the ci into parts

commands/serve/web/render-fixture.js
Loading types from nebula config. Needed for layout container to render children in fixtures
=> feat: load config types for fixtures

apis/supernova/src/creator.js, apis/supernova/src/hooks.js
=> feat: add menuBuilder

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
chore(translations): UI bus - 2023-06-20
- Update translations related to: 4eb69e9 - fix: screen reader search (#1293)
=> chore(translations): UI bus - 2023-06-20

apis/stardust/api-spec/spec.conf.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/supernova/src/hooks.js
=> chore: fix emitter type

apis/nucleus/src/components/ActionsToolbar.jsx, apis/nucleus/src/components/__tests__/actions-toolbar.test.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/default-properties.js, apis/nucleus/src/components/listbox/interactions/listbox-get-action-props.js, apis/nucleus/src/object/__tests__/filterpane-handler.test.js, apis/stardust/api-spec/listbox-spec.json, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
Automatically confirm selections instead of showing the actions toolbar, when `autoConfirm` is true.
=> feat: implement auto confirm

apis/conversion/src/index.js, apis/nucleus/src/__tests__/viz.test.js, apis/nucleus/src/index.js, apis/nucleus/src/utils/can-set-properties.js, apis/nucleus/src/utils/save-soft-properties.js, apis/nucleus/src/utils/set-properties.js, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/supernova/src/index.js
=> feat: object conversion for readonly charts

apis/enigma-mocker/src/mocks/create-session-object-mock.js, apis/nucleus/src/__tests__/viz.test.js, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/sheet.js, apis/nucleus/src/viz.js
Fixes bugs with unresolved promises that stops the viz/sheet API to return properly.
Adds errors for incorrect elements.
=> fix: unresolving promises for missing types

commands/build/lib/config.js, commands/create/templates/mashup/_package.json
"use client" warnings coming from MUI bundling
=> feat: supress "use client" warnings in charts build with nebula build

apis/nucleus/src/__tests__/viz.test.js, apis/nucleus/src/index.js, apis/nucleus/src/sn/__tests__/types.test.js, apis/nucleus/src/sn/types.js, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
Adds support for toggleDataView. Needed to provide an accessible way to the data in Nebula mashups. 
=> feat: toggle data view

apis/nucleus/src/__tests__/viz.test.js, apis/nucleus/src/index.js, apis/nucleus/src/sn/__tests__/types.test.js, apis/nucleus/src/sn/types.js, apis/nucleus/src/viz.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
This reverts commit c8b0d1b3c3605c36b899aa8b2a18b86d92797d56.
=> revert: "feat: toggle data view (#1376)"

rollup.config.js
New Rollup version added some irrelevant warnings, lets suppress.
=> chore: suppress warnings

apis/enigma-mocker/src/__tests__/from-generic-objects.test.js, apis/enigma-mocker/src/from-generic-objects.js, apis/enigma-mocker/src/mocks/create-session-object-mock.js
Session on the app is used by some implemtations
=> feat: add session to mocked app

apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, commands/build/README.md, commands/build/lib/config.js, commands/build/lib/init-config.js
the KPI needs to be able to add the option inlineDynamicImports for code-splitting builds
=> feat: add option to inlineDynamicImports

apis/nucleus/src/index.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/supernova/src/hooks.js
Fixes some typings on the generic load function as well as descrioptions for hooks.
=> chore: fix typings and descriptions

commands/build/README.md, commands/build/lib/build.js, commands/build/lib/config.js, commands/build/lib/init-config.js
=> feat: add option codeSplit to allow for code-splitting

commands/serve/lib/webpack.serve.js, commands/serve/web/__tests__/connect.test.js, commands/serve/web/components/Hub/SelectEngine/ConnectionGuid.jsx, commands/serve/web/components/Hub/SelectEngine/__tests__/ConnectionGuid.test.jsx, commands/serve/web/components/Hub/SelectEngine/__tests__/SelectEngine.test.jsx, commands/serve/web/connect.js
Fix for https://github.com/qlik-oss/nebula.js/issues/1448
=> fix: allow prefix in serve

apis/nucleus/src/__tests__/nucleus.test.js, apis/nucleus/src/index.js
Enables the flag that turns on icons in the KPI
=> chore: enable kpi flag

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
chore(translations): UI bus - 2024-02-02
- Update translations related to: 5e35fb6 - feat(ListBox): break out header and add unlock button (#1466)
=> chore(translations): UI bus - 2024-02-02

commands/serve/lib/oauth-router.js, commands/serve/lib/webpack.serve.js, commands/serve/web/components/Hub/Errors/OAuthRedirectLinkError.jsx, commands/serve/web/components/Hub/SelectEngine/ConnectionGuid.jsx, commands/serve/web/components/Hub/SelectEngine/SelectEngine.jsx, commands/serve/web/components/Hub/styles.js, commands/serve/web/components/Root.jsx, commands/serve/web/connect.js, commands/serve/web/hooks/index.js, commands/serve/web/hooks/useDeauthorizePrevOAuthInstance.js, commands/serve/web/hooks/useOpenApp.js, commands/serve/web/utils/authRequests.js
=> fix(cli-serve): OAuth instance cache issue

apis/nucleus/src/__tests__/nucleus.test.js, apis/nucleus/src/index.js
=> chore: another flag

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
chore(translations): UI bus - 2024-03-08
- Update translations related to: f35a5c4 - feat(ListBoxHeader): add icon for cyclic dimension and new drilldown icon (#1504)
=> chore(translations): UI bus - 2024-03-08

apis/test-utils/package.json, commands/cli/package.json, commands/create/templates/sn/none/_package.json, commands/create/templates/sn/picasso/common/_package.json, examples/sn-hello-react/package.json
=> chore: set all peers to v5

apis/nucleus/src/components/listbox/components/ListBoxSearch.jsx, apis/nucleus/src/components/listbox/components/__tests__/list-box-search.test.jsx, apis/supernova/src/hooks.js, commands/build/lib/config.js
=> fix: broken search

apis/supernova/src/hooks.js, commands/build/lib/config.js
=> fix: remove unwanted console loggin

apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/ListBoxPopover.jsx
=> fix: optional chaining for checking flag in listbox

apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
=> refactor: update spec

apis/nucleus/src/object/navigation/navigation.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/supernova/src/hooks.js
=> refactor: update navigation specs

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
chore(translations): UI bus - 2024-08-06
- Update translations related to: 1a92d5f - fix: add clear search button to listbox search (#1566)
=> chore(translations): UI bus - 2024-08-06

apis/nucleus/src/components/ActionsToolbar.jsx, apis/nucleus/src/components/ActionsToolbarMore.jsx, apis/nucleus/src/components/listbox/ListBoxInline.jsx, apis/nucleus/src/components/listbox/components/ListBoxHeader/ListBoxHeader.jsx, apis/nucleus/src/components/listbox/interactions/listbox-action-props.js
to get the fix from #1568 for cases where needed
but not when it causes the problem that caused it to be reverted (in #1593)
=> feat: disable portal option

apis/nucleus/src/index.js, apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts
jsdocs was not picking up that load was set to optional (putting a `=` last) so had to break it out
=> fix: correct type for load fallback function in embed config

apis/nucleus/src/components/selections/MultiState.jsx, apis/nucleus/src/components/selections/OneField.jsx, apis/nucleus/src/components/selections/SelectedFields.jsx, apis/nucleus/src/components/selections/__tests__/one-field.test.jsx, apis/nucleus/src/components/selections/__tests__/selected-fields.test.jsx
Refactor handling of user-created labels
and extend it fully to support multi-state selections.
=> feat: dimension labels in selection bar

commands/build/lib/systemjs.js
Use regex to correctly match sub-imports as well.
=> chore: use regex for qmfe matching

apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/supernova/src/__tests__/hooks.test.js, apis/supernova/src/hooks.js
Adds a useRef hook that works similarly to the preact/react counterpart.
=> feat: add useRef

apis/nucleus/src/index.js
=> fix: move options into __DO_NOT_USE__

apis/theme/src/contraster/__tests__/luminance.test.js, apis/theme/src/contraster/luminance.js
Fix issue with incorrect colors in theme causing a crash.
=> fix: avoid crash if color is invalid

commands/create/templates/mashup/_package.json
Reverts flag removal to see if it resolve the build issues
=> chore: update parcel in template

apis/enigma-mocker/src/from-generic-objects.js, apis/enigma-mocker/src/mocks/get-object-mock.js
=> feat: update mocks

apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/supernova/src/qae.js
(yarn spec have problems. I needed to run it 5-6 times to get minimal diff, before that it also include moving type around for no reasons)
=> fix: type error for properties in QAEDefinition

apis/theme/src/palette-resolver.js
Some bad themes causes a crash
=> fix: guard against bad theme

apis/supernova/src/generator.js
=> fix: remove ext from generator

apis/nucleus/src/hooks/useStyling.js
=> fix: map visualization to theme object type

apis/nucleus/src/components/NebulaApp.jsx, apis/nucleus/src/components/glue.jsx, apis/nucleus/src/components/listbox/hooks/useExistingModel.jsx, apis/nucleus/src/components/sheetGlue.jsx
Fix lingering event listener in sheet
=> fix: sheet destroy

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/Sheet.jsx
Move fallback emitter to Cell instead of sheet to avoid re-creating it.
=> fix: instead add emitter in Cell

commands/serve/web/components/Hub/SelectEngine/ConnectionGuid.jsx, commands/serve/web/connect.js, commands/serve/web/hooks/useOpenApp.js, commands/serve/web/utils/getCsrfToken.js
=> fix: check for no prefix and update help text

apis/nucleus/src/hooks/useLayout.js
Fixes a compatability issues with the Sense mixins.
=> fix: work with client mixins

apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/hooks/useStyling.js, apis/nucleus/src/utils/style/__tests__/styling-props.test.js, apis/nucleus/src/utils/style/styling-props.js
=> feat: add support for disableThemeBorder option

apis/nucleus/src/components/ActionsToolbar.jsx, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/FiltersFooter.jsx, apis/nucleus/src/components/Footer.jsx, apis/nucleus/src/components/Header.jsx
Add rtl support for title, subtitle, footer and action toolbar.
=> feat: add rtl support

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
chore(translations): UI bus - 2025-05-06
- Update translations related to: 6b84132 - fix: add filters info in footnote (#1710)
=> chore(translations): UI bus - 2025-05-06

apis/nucleus/src/utils/__tests__/cell-padding.test.js, apis/nucleus/src/utils/cell-padding.js
found that padding/spacing was still different then in sense-client after: https://github.com/qlik-oss/nebula.js/pull/1690
mostly for button object
change to compromise between more like sense-client and make it simpler
=> fix: more cell spacing fixes

apis/nucleus/src/components/NebulaApp.jsx
Remove root element when destroying instance
=> chore: remove element when destroyed

apis/locale/locales/en-US.json, apis/nucleus/src/components/Cell.jsx, apis/nucleus/src/components/Header.jsx, apis/nucleus/src/components/Supernova.jsx, apis/nucleus/src/components/__tests__/cell.test.jsx, apis/nucleus/src/components/__tests__/header.test.jsx, apis/nucleus/src/components/__tests__/supernova.test.jsx, apis/nucleus/src/components/listbox/components/__tests__/list-box-header.test.jsx, apis/nucleus/src/utils/extension-translation-keys.js, apis/nucleus/src/utils/style/screen-reader.js
Support screen reader in gridless sheet. This will probably support screen reader for embed of object too. Not nice to put translation for all objects here but it is faster doing this. 
=> feat: support screen reader in gridless sheet

apis/locale/locales/de.json, apis/locale/locales/es.json, apis/locale/locales/fr.json, apis/locale/locales/it.json, apis/locale/locales/ja.json, apis/locale/locales/ko.json, apis/locale/locales/nl.json, apis/locale/locales/pl.json, apis/locale/locales/pt.json, apis/locale/locales/ru.json, apis/locale/locales/sv.json, apis/locale/locales/tr.json, apis/locale/locales/zh-CN.json, apis/locale/locales/zh-TW.json
chore(translations): UI bus - 2025-06-06
- Update translations related to: ffdbab0 - feat: support screen reader in gridless sheet (#1756)
=> chore(translations): UI bus - 2025-06-06

apis/stardust/api-spec/spec.json, apis/stardust/types/index.d.ts, apis/supernova/src/handler/utils/field-helper/field-utils.js
Removes an incorrect addion to the spec
=> docs: remove incorrect spec addition

.github/workflows/ci.yml
=> chore: api-gov gh

README.md
Makes sure the @qlik/api dependency addition ends up in the changelong as it can potentially impact the import of the library.
=> chore!: add dependency to @qlik/api

apis/supernova/src/handler/data-property-handler.js
=> chore: remove lodash

commands/build/lib/config.js, commands/build/lib/init-config.js, commands/build/lib/systemjs.js
=> fix: support qlik/api

commands/build/lib/config.js
=> fix: try support css modules

commands/build/lib/config.js, commands/build/package.json, yarn.lock
=> chore: add babel dependencies to cli-build

babel.config.cjs, commands/build/lib/config.js
=> chore: proper import of babel plugins

apis/nucleus/src/hooks/useStyling.js
=> fix: allow generic styling sn-table through theme
